"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from ..chat.chat_completion import ChatCompletion
from ..bot_chat.bot_reference import Reference
from ..bot_chat.bot_usage import BotUsage

__all__ = ["BotChatCompletion"]
class BotChatCompletion(ChatCompletion):
    bot_usage: Optional[BotUsage] = ...
    references: Optional[List[Reference]] = ...
    metadata: Optional[Dict[str, object]] = ...


