"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from ..chat.chat_completion_chunk import ChatCompletionChunk
from ..bot_chat.bot_reference import Reference
from ..bot_chat.bot_usage import BotUsage

__all__ = ["BotChatCompletionChunk"]
class BotChatCompletionChunk(ChatCompletionChunk):
    bot_usage: Optional[BotUsage] = ...
    references: Optional[List[Reference]] = ...
    metadata: Optional[Dict[str, object]] = ...


