"""
This type stub file was generated by pyright.
"""

import httpx
from typing import TYPE_CHECKING
from typing_extensions import Literal
from zai.core import BaseAPI, Body, FileTypes, Headers, NotGiven
from zai.types.file_parser.file_parser_resp import FileParserTaskCreateResp, FileParsingDownloadResp
from zai._client import ZaiClient

if TYPE_CHECKING:
    ...
__all__ = ["FileParser"]
class FileParser(BaseAPI):
    def __init__(self, client: ZaiClient) -> None:
        ...
    
    def create(self, *, file: FileTypes = ..., file_type: str = ..., tool_type: Literal["lite", "expert", "prime"], extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> FileParserTaskCreateResp:
        ...
    
    def content(self, task_id: str, *, format_type: Literal["text", "download_link"], extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> httpx.Response:
        """
        Returns the contents of the specified file.

        Args:
          extra_headers: Send extra headers

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def create_sync(self, *, file: FileTypes = ..., file_type: str = ..., tool_type: Literal["prime-sync"], extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> FileParsingDownloadResp:
        ...
    


