"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["MultimodalEmbeddingContentPartImageParam", "ImageURL"]
class ImageURL(TypedDict, total=False):
    url: Required[str]
    ...


class MultimodalEmbeddingContentPartImageParam(TypedDict, total=False):
    image_url: Required[ImageURL]
    type: Required[Literal["image_url"]]
    ...


