"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from .embedding_data import MultimodalEmbedding
from .embedding_usage import MultimodalEmbeddingUsage
from ..._models import BaseModel

__all__ = ["MultimodalEmbeddingResponse"]
class MultimodalEmbeddingResponse(BaseModel):
    id: str
    created: int
    data: MultimodalEmbedding
    model: str
    object: Literal["list"]
    usage: MultimodalEmbeddingUsage
    ...


