"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from typing import Optional

__all__ = ["MultimodalEmbeddingUsage", "PromptTokensDetails"]
class PromptTokensDetails(BaseModel):
    text_tokens: int
    image_tokens: int
    ...


class MultimodalEmbeddingUsage(BaseModel):
    prompt_tokens: int
    total_tokens: int
    prompt_tokens_details: Optional[PromptTokensDetails] = ...


