"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["MultimodalEmbedding", "SparseEmbedding"]
class SparseEmbedding(BaseModel):
    index: int
    value: float
    ...


class MultimodalEmbedding(BaseModel):
    embedding: List[float]
    object: Literal["embedding"]
    sparse_embedding: Optional[SparseEmbedding] = ...


