"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["SparseEmbeddingInput"]
class SparseEmbeddingInput(TypedDict, total=False):
    type: Required[Literal["enabled", "disabled"]]
    ...


