"""
This type stub file was generated by pyright.
"""

import datetime
from typing import Optional, Union
from typing_extensions import Literal, Required, TypedDict

__all__ = ["TruncationStrategy", "TTLTypes", "to_optional_ttl"]
class TruncationStrategy(TypedDict, total=False):
    type: Required[Literal["last_history_tokens", "rolling_tokens"]]
    last_history_tokens: Optional[int]
    rolling_tokens: Optional[bool]
    ...


TTLTypes = Union[int, datetime.timedelta]
def to_optional_ttl(ttl: TTLTypes | None) -> int | None:
    ...

