"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel
from ..chat.chat_completion_chunk import Choice
from ..completion_usage import CompletionUsage

__all__ = ["ContextChatCompletionChunk"]
class ContextChatCompletionChunk(BaseModel):
    id: str
    choices: List[Choice]
    created: int
    model: str
    object: Literal["chat.completion.chunk"]
    usage: Optional[CompletionUsage] = ...


