"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel
from ..chat.chat_completion import Choice
from ..completion_usage import CompletionUsage

__all__ = ["ContextChatCompletion"]
class ContextChatCompletion(BaseModel):
    id: str
    choices: List[Choice]
    created: int
    model: str
    object: Literal["chat.completion"]
    usage: Optional[CompletionUsage] = ...


