"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel
from ..completion_usage import CompletionUsage
from .truncation_strategy import TruncationStrategy

__all__ = ["CreateContextResponse"]
class CreateContextResponse(BaseModel):
    id: str
    model: str
    mode: str
    ttl: int
    truncation_strategy: TruncationStrategy
    usage: CompletionUsage
    ...


