"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["TruncationStrategy"]
class TruncationStrategy(BaseModel):
    type: Literal["last_history_tokens"]
    last_history_tokens: Optional[int] = ...


