"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional
from typing_extensions import Literal, overload
from ..._types import Body, Headers, NotGiven, Query
from ..._utils._utils import apikey_required, async_apikey_required
from ..._resource import AsyncAPIResource, SyncAPIResource
from ...types.images import ImagesResponse, OptimizePromptOptions, SequentialImageGenerationOptions
from ...types.images.image_gen_stream_event import ImageGenStreamEvent
from ..._streaming import Stream
from ...types.images.images import OptimizePromptOptions

class Images(SyncAPIResource):
    @overload
    def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Optional[Literal[False]] | NotGiven = ...) -> ImagesResponse:
        ...
    
    @overload
    def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Literal[True]) -> Stream[ImageGenStreamEvent]:
        ...
    
    @overload
    def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: bool) -> ImagesResponse | Stream[ImageGenStreamEvent]:
        ...
    
    @apikey_required
    def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Optional[Literal[False]] | Literal[True] | NotGiven = ...) -> ImagesResponse | Stream[ImageGenStreamEvent]:
        ...
    


class AsyncImages(AsyncAPIResource):
    @overload
    async def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Optional[Literal[False]] | NotGiven = ...) -> ImagesResponse:
        ...
    
    @overload
    async def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Literal[True]) -> Stream[ImageGenStreamEvent]:
        ...
    
    @overload
    async def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: bool) -> ImagesResponse | Stream[ImageGenStreamEvent]:
        ...
    
    @async_apikey_required
    async def generate(self, *, model: str, prompt: str, image: str | list[str] | None = ..., response_format: str | None = ..., size: str | None = ..., seed: int | None = ..., guidance_scale: float | None = ..., watermark: bool | None = ..., optimize_prompt: bool | None = ..., optimize_prompt_options: OptimizePromptOptions | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ..., sequential_image_generation: str | None = ..., sequential_image_generation_options: SequentialImageGenerationOptions | None = ..., stream: Optional[Literal[False]] | Literal[True] | NotGiven = ...) -> ImagesResponse | Stream[ImageGenStreamEvent]:
        ...
    


