"""
This type stub file was generated by pyright.
"""

import asyncio
import threading
from httpx import AsyncClient, Client, Timeout, URL
from typing import Dict, Optional, Tuple
from ._models import BaseModel
from . import resources
from .resources.beta import beta
from .resources.batch import batch
from ._base_client import AsyncAPIClient, SyncAPIClient
from ._utils._key_agreement import key_agreement_client
from ._utils._model_breaker import ModelBreaker

__all__ = ["Ark", "AsyncArk"]
class Ark(SyncAPIClient):
    beta: beta.Beta
    chat: resources.Chat
    bot_chat: resources.BotChat
    embeddings: resources.Embeddings
    tokenization: resources.Tokenization
    context: resources.Context
    multimodal_embeddings: resources.MultimodalEmbeddings
    content_generation: resources.ContentGeneration
    images: resources.Images
    batch_chat: resources.BatchChat
    responses: resources.Responses
    input_items: resources.InputItems
    batch: batch.Batch
    model_breaker_map: dict[str, ModelBreaker]
    model_breaker_lock: threading.Lock
    files: resources.Files
    def __init__(self, *, base_url: str | URL = ..., ak: str | None = ..., sk: str | None = ..., api_key: str | None = ..., region: str = ..., timeout: float | Timeout | None = ..., max_retries: int = ..., http_client: Client | None = ...) -> None:
        """init ark client, this client is thread unsafe. If need to use in multi thread, init a new `Ark` client in
        each thread

            Args:
                ak: access key id
                sk: secret access key
                api_key: api key，this api key will not be refreshed
                timeout: timeout of client. default httpx.Timeout(timeout=60.0, connect=60.0)
                max_retries: times of retry when request failed. default 1
                http_client: specify customized http_client
            Returns:
                ark client
        """
        ...
    
    @property
    def auth_headers(self) -> dict[str, str]:
        ...
    
    def get_model_breaker(self, model_name: str) -> ModelBreaker:
        ...
    


class AsyncArk(AsyncAPIClient):
    beta: beta.AsyncBeta
    chat: resources.AsyncChat
    bot_chat: resources.AsyncBotChat
    embeddings: resources.AsyncEmbeddings
    tokenization: resources.AsyncTokenization
    context: resources.AsyncContext
    multimodal_embeddings: resources.AsyncMultimodalEmbeddings
    content_generation: resources.AsyncContentGeneration
    images: resources.AsyncImages
    batch_chat: resources.AsyncBatchChat
    responses: resources.AsyncResponses
    input_items: resources.AsyncInputItems
    batch: batch.AsyncBatch
    model_breaker_map: dict[str, ModelBreaker]
    model_breaker_lock: asyncio.Lock
    files: resources.AsyncFiles
    def __init__(self, *, ak: str | None = ..., sk: str | None = ..., api_key: str | None = ..., base_url: str | URL = ..., region: str = ..., timeout: float | Timeout | None = ..., max_retries: int = ..., http_client: AsyncClient | None = ...) -> None:
        """init async ark client, this client is thread unsafe

        Args:
            ak: access key id
            sk: secret access key
            api_key: api key，this api key will not be refreshed
            timeout: timeout of client. default httpx.Timeout(timeout=60.0, connect=60.0)
            max_retries: times of retry when request failed. default 1
            http_client: specify customized http_client
        Returns:
            async ark client
        """
        ...
    
    @property
    def auth_headers(self) -> dict[str, str]:
        ...
    
    async def get_model_breaker(self, model_name: str) -> ModelBreaker:
        ...
    


class StsTokenManager:
    _advisory_refresh_timeout: int = ...
    _mandatory_refresh_timeout: int = ...
    def __init__(self, ak: str, sk: str, region: str) -> None:
        ...
    
    def get(self, ep: str, resource_type: str = ...) -> str:
        ...
    


class CertificateResponse(BaseModel):
    error: Optional[Dict[str, str]] = ...
    Certificate: str


class E2ECertificateManager:
    def __init__(self, ak: str, sk: str, region: str, base_url: str | URL = ..., api_key: str | None = ...) -> None:
        ...
    
    def get(self, ep: str) -> Tuple[key_agreement_client, str, str, float]:
        ...
    


