"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from typing_extensions import Literal
from .types.chat import ChatCompletion

if TYPE_CHECKING:
    ...
__all__ = ["ArkBadRequestError", "ArkAuthenticationError", "ArkPermissionDeniedError", "ArkNotFoundError", "ArkConflictError", "ArkUnprocessableEntityError", "ArkRateLimitError", "ArkInternalServerError"]
class ArkError(Exception):
    ...


class ArkAPIError(ArkError):
    message: str
    request: Optional[httpx.Request] = ...
    body: Optional[object] = ...
    request_id: Optional[str] = ...
    code: Optional[str] = ...
    param: Optional[str] = ...
    type: Optional[str]
    def __init__(self, message: str, request: Optional[httpx.Request] = ..., *, body: Optional[object] = ..., request_id: Optional[str] = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class ArkAPIResponseValidationError(ArkAPIError):
    response: httpx.Response
    status_code: int
    def __init__(self, response: httpx.Response, body: object | None, *, message: str | None = ..., request_id: str) -> None:
        ...
    


class ArkAPIStatusError(ArkAPIError):
    """Raised when an API response has a status code of 4xx or 5xx."""
    response: httpx.Response
    status_code: int
    def __init__(self, message: str, *, response: httpx.Response, body: object | None, request_id: str) -> None:
        ...
    


class ArkAPIConnectionError(ArkAPIError):
    def __init__(self, *, message: str = ..., request: httpx.Request, request_id: str) -> None:
        ...
    


class ArkAPITimeoutError(ArkAPIConnectionError):
    def __init__(self, request: httpx.Request, request_id: str) -> None:
        ...
    


class ArkBadRequestError(ArkAPIStatusError):
    status_code: Literal[400] = ...


class ArkAuthenticationError(ArkAPIStatusError):
    status_code: Literal[401] = ...


class ArkPermissionDeniedError(ArkAPIStatusError):
    status_code: Literal[403] = ...


class ArkNotFoundError(ArkAPIStatusError):
    status_code: Literal[404] = ...


class ArkConflictError(ArkAPIStatusError):
    status_code: Literal[409] = ...


class ArkUnprocessableEntityError(ArkAPIStatusError):
    status_code: Literal[422] = ...


class ArkRateLimitError(ArkAPIStatusError):
    status_code: Literal[429] = ...


class ArkInternalServerError(ArkAPIStatusError):
    ...


class ArkLengthFinishReasonError(ArkError):
    completion: ChatCompletion
    def __init__(self, *, completion: ChatCompletion) -> None:
        ...
    


class ArkContentFilterFinishReasonError(ArkError):
    def __init__(self) -> None:
        ...
    


