"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Mapping, Tuple, TypeVar, Union
from typing_extensions import Literal
from ._types import NotGivenOr

_T = TypeVar("_T")
ArrayFormat = Literal["comma", "repeat", "indices", "brackets"]
NestedFormat = Literal["dots", "brackets"]
PrimitiveData = Union[str, int, float, bool, None]
Data = Union[PrimitiveData, List[Any], Tuple[Any], "Mapping[str, Any]"]
Params = Mapping[str, Data]
class Querystring:
    array_format: ArrayFormat
    nested_format: NestedFormat
    def __init__(self, *, array_format: ArrayFormat = ..., nested_format: NestedFormat = ...) -> None:
        ...
    
    def parse(self, query: str) -> Mapping[str, object]:
        ...
    
    def stringify(self, params: Params, *, array_format: NotGivenOr[ArrayFormat] = ..., nested_format: NotGivenOr[NestedFormat] = ...) -> str:
        ...
    
    def stringify_items(self, params: Params, *, array_format: NotGivenOr[ArrayFormat] = ..., nested_format: NotGivenOr[NestedFormat] = ...) -> list[tuple[str, str]]:
        ...
    


_qs = ...
parse = ...
stringify = ...
stringify_items = ...
class Options:
    array_format: ArrayFormat
    nested_format: NestedFormat
    def __init__(self, qs: Querystring = ..., *, array_format: NotGivenOr[ArrayFormat] = ..., nested_format: NotGivenOr[NestedFormat] = ...) -> None:
        ...
    


