"""
This type stub file was generated by pyright.
"""

import pydantic
from typing import Any, Callable, TYPE_CHECKING, Union
from httpx import Timeout
from typing_extensions import ClassVar, Required, TypedDict, Unpack
from ._compat import ConfigDict, PYDANTIC_V2
from ._models import BaseModel
from ._types import AnyMapping, Body, Headers, HttpxRequestFiles, NotGiven, Query

__all__ = ["ExtraRequestOptions", "RequestOptions"]
if TYPE_CHECKING:
    ...
class ExtraRequestOptions(TypedDict, total=False):
    method: Required[str]
    url: Required[str]
    params: Query
    headers: Headers
    max_retries: int
    timeout: float | Timeout | None
    files: HttpxRequestFiles | None
    idempotency_key: str
    json_data: Body
    extra_body: AnyMapping
    ...


class RequestOptions(BaseModel):
    method: str
    url: str
    body: Union[object, None] = ...
    params: Query = ...
    headers: Union[Headers, NotGiven] = ...
    max_retries: Union[int, NotGiven] = ...
    timeout: Union[float, Timeout, None, NotGiven] = ...
    files: Union[HttpxRequestFiles, None] = ...
    idempotency_key: Union[str, None] = ...
    post_parser: Union[Callable[[Any], Any], NotGiven] = ...
    json_data: Union[Body, None] = ...
    extra_body: Union[AnyMapping, None] = ...
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ...
    else:
        class Config(pydantic.BaseConfig):
            arbitrary_types_allowed: bool = ...
        
        
    def get_max_retries(self, max_retries: int) -> int:
        ...
    
    @classmethod
    def construct(cls, _fields_set: set[str] | None = ..., **values: Unpack[ExtraRequestOptions]) -> RequestOptions:
        ...
    
    if not TYPE_CHECKING:
        ...


