"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ._client import Ark, AsyncArk

if TYPE_CHECKING:
    ...
class SyncAPIResource:
    _client: Ark
    def __init__(self, client: Ark) -> None:
        ...
    


class AsyncAPIResource:
    _client: AsyncArk
    def __init__(self, client: AsyncArk) -> None:
        ...
    


