"""
This type stub file was generated by pyright.
"""

from .tasks import AsyncTasks, Tasks
from ..._compat import cached_property
from ..._resource import AsyncAPIResource, SyncAPIResource

class ContentGeneration(SyncAPIResource):
    @cached_property
    def tasks(self) -> Tasks:
        ...
    


class AsyncContentGeneration(AsyncAPIResource):
    @cached_property
    def tasks(self) -> AsyncTasks:
        ...
    


