"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Iterable, List, Optional, Union
from volcenginesdkarkruntime._resource import AsyncAPIResource, SyncAPIResource
from volcenginesdkarkruntime.types.content_generation.create_task_content_param import CreateTaskContentParam
from ..._compat import cached_property
from ..._types import Body, Headers, Query
from ..._utils._utils import apikey_required, async_apikey_required
from ...types.content_generation.content_generation_task import ContentGenerationTask
from ...types.content_generation.content_generation_task_id import ContentGenerationTaskID
from ...types.content_generation.list_content_generation_tasks_response import ListContentGenerationTasksResponse

class Tasks(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> TasksWithRawResponse:
        ...
    
    @apikey_required
    def create(self, *, model: str, content: Iterable[CreateTaskContentParam], callback_url: Optional[str] = ..., return_last_frame: Optional[bool] = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContentGenerationTaskID:
        ...
    
    @apikey_required
    def get(self, *, task_id: str, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContentGenerationTask:
        ...
    
    @apikey_required
    def list(self, page_num: int | None = ..., page_size: int | None = ..., status: str | None = ..., task_ids: Union[List[str], str] | None = ..., model: str | None = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., extra_query: Query | None = ..., timeout: float | httpx.Timeout | None = ...) -> ListContentGenerationTasksResponse:
        ...
    
    @apikey_required
    def delete(self, task_id: str, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> None:
        ...
    


class AsyncTasks(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncTasksWithRawResponse:
        ...
    
    @async_apikey_required
    async def create(self, *, model: str, content: Iterable[CreateTaskContentParam], callback_url: Optional[str] = ..., return_last_frame: Optional[bool] = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContentGenerationTaskID:
        ...
    
    @async_apikey_required
    async def get(self, *, task_id: str, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContentGenerationTask:
        ...
    
    @async_apikey_required
    async def list(self, page_num: int | None = ..., page_size: int | None = ..., status: str | None = ..., task_ids: Union[List[str], str] | None = ..., model: str | None = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., extra_query: Query | None = ..., timeout: float | httpx.Timeout | None = ...) -> ListContentGenerationTasksResponse:
        ...
    
    @async_apikey_required
    async def delete(self, task_id: str, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> None:
        ...
    


class TasksWithRawResponse:
    def __init__(self, tasks: Tasks) -> None:
        ...
    


class AsyncTasksWithRawResponse:
    def __init__(self, tasks: AsyncTasks) -> None:
        ...
    


