"""
This type stub file was generated by pyright.
"""

from typing import Optional
from zai.core import BaseModel

class BatchError(BaseModel):
	"""
	Represents an error that occurred during batch processing.

	Attributes:
		code (Optional[str]): Defined business error code
		line (Optional[int]): Line number in the file where the error occurred
		message (Optional[str]): Description of the error in the conversation file
		param (Optional[str]): Parameter that caused the error
	"""
	code: Optional[str] = ...
	line: Optional[int] = ...
	message: Optional[str] = ...
	param: Optional[str] = ...


