"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Literal, Required, TypedDict

class BatchCreateParams(TypedDict, total=False):
	completion_window: Required[str]
	endpoint: Required[Literal['/v1/chat/completions', '/v1/embeddings']]
	input_file_id: Required[str]
	metadata: Optional[Dict[str, str]]
	auto_delete_input_file: Optional[bool]
	...


