"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.voiceclone import VoiceCloneResult, VoiceDeleteResult, VoiceListResult
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Voice(BaseAPI):
	"""
	Voice API resource for handling voice cloning operations
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def clone(self, *, voice_name: str, text: str, input: str, file_id: str, request_id: Optional[str] = ..., model: str, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> VoiceCloneResult:
		"""
		Clone a voice with the provided audio sample and parameters

		Args:
			voice_name: Name for the cloned voice
			text: Text content corresponding to the sample audio
			input: Target text for preview audio
			file_id: File ID of the uploaded audio file
			request_id: Optional request ID for tracking
			model: Model
			extra_headers: Additional headers to include in the request
			extra_body: Additional body parameters
			timeout: Request timeout

		Returns:
			Voice clone response
		"""
		...
	
	def delete(self, *, voice: str, request_id: Optional[str] = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> VoiceDeleteResult:
		"""
		Delete a cloned voice by voice ID
		
		Args:
			voice: The voice to delete
			request_id: Optional request ID for tracking
			extra_headers: Additional headers to include in the request
			extra_body: Additional body parameters
			timeout: Request timeout
			
		Returns:
			Voice deletion response
		"""
		...
	
	def list(self, *, voice_type: Optional[str] = ..., voice_name: Optional[str] = ..., request_id: Optional[str] = ..., extra_headers: Headers | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> VoiceListResult:
		"""
		List voices with optional filtering
		
		Args:
			voice_type: Type of voice to filter by
			voice_name: Name of voice to filter by
			request_id: Optional request ID for tracking
			extra_headers: Additional headers to include in the request
			timeout: Request timeout
			
		Returns:
			List of voices response
		"""
		...
	


