"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import Any, List, Optional, Union
from pymilvus.client.types import DataType

"""EmbeddingList: A container for multiple embeddings for array-of-vector searches."""
class EmbeddingList:
    """
    A container for multiple embeddings that can be used directly in Milvus searches.
    Represents a single query containing multiple vectors for array-of-vector fields.

    This is particularly useful for searching struct array fields that contain vectors,
    enabling array-of-vector to array-of-vector searches.

    Examples:
        >>> # Create empty and add vectors
        >>> query1 = EmbeddingList()
        >>> query1.add(embedding1)
        >>> query1.add(embedding2)
        >>>
        >>> # Create from list of vectors
        >>> vectors = [vec1, vec2, vec3]
        >>> query2 = EmbeddingList(vectors)
        >>>
        >>> # Use in search
        >>> results = client.search(
        >>>     collection_name="my_collection",
        >>>     data=[query1, query2],  # List of EmbeddingList
        >>>     ...
        >>> )
    """
    def __init__(self, embeddings: Optional[Union[List[np.ndarray], np.ndarray]] = ..., dim: Optional[int] = ..., dtype: Optional[Union[np.dtype, str, DataType]] = ...) -> None:
        """
        Initialize an EmbeddingList.

        Args:
            embeddings: Initial embeddings. Can be:
                - None: Creates an empty list
                - np.ndarray with shape (n, dim): Batch of n embeddings
                - np.ndarray with shape (dim,): Single embedding
                - List[np.ndarray]: List of embedding arrays
            dim: Expected dimension for validation (optional).
                 If provided, all added embeddings will be validated against this dimension.
            dtype: Data type of the embeddings (optional). Can be:
                - numpy dtype (e.g., np.float32, np.float16, np.uint8)
                - string (e.g., 'float32', 'float16', 'uint8')
                - DataType enum (e.g., DataType.FLOAT_VECTOR, DataType.BINARY_VECTOR)
                If not specified, will infer from the first embedding added.
        """
        ...
    
    def add(self, embedding: Union[np.ndarray, List[Any]]) -> EmbeddingList:
        """
        Add a single embedding vector to the list.

        Args:
            embedding: A single embedding vector (1D array or list)

        Returns:
            Self for method chaining

        Raises:
            ValueError: If embedding dimension doesn't match existing embeddings
        """
        ...
    
    def add_batch(self, embeddings: Union[List[np.ndarray], np.ndarray]) -> EmbeddingList:
        """
        Add multiple embeddings at once.

        Args:
            embeddings: Batch of embeddings (2D array or list of 1D arrays)

        Returns:
            Self for method chaining

        Raises:
            ValueError: If embeddings have inconsistent dimensions
        """
        ...
    
    def to_flat_array(self) -> np.ndarray:
        """
        Convert to flat array format required by Milvus for array-of-vector fields.

        Returns:
            Flattened numpy array containing all embeddings concatenated

        Raises:
            ValueError: If the list is empty
        """
        ...
    
    def to_numpy(self) -> np.ndarray:
        """
        Convert to 2D numpy array.

        Returns:
            2D numpy array with shape (num_embeddings, dim)

        Raises:
            ValueError: If the list is empty
        """
        ...
    
    def clear(self) -> EmbeddingList:
        """Clear all embeddings from the list."""
        ...
    
    def __len__(self) -> int:
        """Return the number of embeddings in the list."""
        ...
    
    def __getitem__(self, index: int) -> np.ndarray:
        """Get embedding at specific index."""
        ...
    
    def __iter__(self): # -> Iterator[ndarray[_AnyShape, dtype[Any]]]:
        """Iterate over embeddings."""
        ...
    
    @property
    def dim(self) -> int:
        """Dimension of each embedding."""
        ...
    
    @property
    def dtype(self) -> Optional[np.dtype]:
        """Data type of the embeddings."""
        ...
    
    @property
    def shape(self) -> tuple:
        """Shape as (num_embeddings, dim)."""
        ...
    
    @property
    def total_dim(self) -> int:
        """Total dimension of all embeddings combined."""
        ...
    
    @property
    def is_empty(self) -> bool:
        """Check if the list is empty."""
        ...
    
    @property
    def nbytes(self) -> int:
        """Total number of bytes used by all embeddings."""
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


