"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["AudioChunkingStrategy"]
class AudioChunkingStrategy(BaseModel):
    type: Literal["server_vad"]
    prefix_padding_ms: Optional[int] = ...
    silence_duration_ms: Optional[int] = ...
    threshold: Optional[float] = ...


