"""
This type stub file was generated by pyright.
"""

from typing import Optional, Union
from typing_extensions import Literal
from ..._models import BaseModel
from .response_input_message_content_list import ResponseInputMessageContentList

__all__ = ["EasyInputMessage"]
class EasyInputMessage(BaseModel):
    content: Union[str, ResponseInputMessageContentList]
    role: Literal["user", "assistant", "system", "developer"]
    type: Optional[Literal["message"]] = ...


