"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Literal, Required, TypedDict
from .response_input_message_content_list_param import ResponseInputMessageContentListParam

__all__ = ["EasyInputMessageParam"]
class EasyInputMessageParam(TypedDict, total=False):
    content: Required[Union[str, ResponseInputMessageContentListParam]]
    role: Required[Literal["user", "assistant", "system", "developer"]]
    type: Literal["message"]
    ...


