"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["FunctionTool"]
class FunctionTool(BaseModel):
    name: str
    parameters: Optional[Dict[str, object]] = ...
    type: Literal["function"]
    description: Optional[str] = ...


