"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["FunctionToolParam"]
class FunctionToolParam(TypedDict, total=False):
    name: Required[str]
    parameters: Required[Optional[Dict[str, object]]]
    type: Required[Literal["function"]]
    description: Optional[str]
    ...


