"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict
from .image_process_grounding_options_param import ImageProcessGroundingOptionsParam
from .image_process_point_options_param import ImageProcessPointOptionsParam
from .image_process_rotate_options_param import ImageProcessRotateOptionsParam
from .image_process_zoom_options_param import ImageProcessZoomOptionsParam

__all__ = ["ImageProcessToolParam"]
class ImageProcessToolParam(TypedDict, total=False):
    type: Required[Literal["image_process"]]
    point: Optional[ImageProcessPointOptionsParam]
    grounding: Optional[ImageProcessGroundingOptionsParam]
    zoom: Optional[ImageProcessZoomOptionsParam]
    rotate: Optional[ImageProcessRotateOptionsParam]
    ...


