"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel

__all__ = ["ImageProcessPointOptions"]
class ImageProcessPointOptions(BaseModel):
    type: Optional[str] = ...


