"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import TypedDict

__all__ = ["ImageProcessPointOptionsParam"]
class ImageProcessPointOptionsParam(TypedDict, total=False):
    type: Optional[str]
    ...


