"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel

__all__ = ["ImageProcessGroundingOptions"]
class ImageProcessGroundingOptions(BaseModel):
    type: Optional[str] = ...


