"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .image_process_grounding_options import ImageProcessGroundingOptions
from .image_process_point_options import ImageProcessPointOptions
from .image_process_rotate_options import ImageProcessRotateOptions
from .image_process_zoom_options import ImageProcessZoomOptions

__all__ = ["ImageProcessTool"]
class ImageProcessTool(BaseModel):
    type: Literal["image_process"]
    point: Optional[ImageProcessPointOptions] = ...
    grounding: Optional[ImageProcessGroundingOptions] = ...
    zoom: Optional[ImageProcessZoomOptions] = ...
    rotate: Optional[ImageProcessRotateOptions] = ...


