"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import TypedDict

__all__ = ["ImageProcessZoomOptionsParam"]
class ImageProcessZoomOptionsParam(TypedDict, total=False):
    type: Optional[str]
    ...


