"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel

__all__ = ["ImageProcessZoomOptions"]
class ImageProcessZoomOptions(BaseModel):
    type: Optional[str] = ...


