"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import Literal, TypedDict
from .response_includable import ResponseIncludable

__all__ = ["InputItemListParams"]
class InputItemListParams(TypedDict, total=False):
    after: str
    before: str
    include: List[ResponseIncludable]
    limit: int
    order: Literal["asc", "desc"]
    ...


