"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .response_image_process_action import ResponseImageProcessAction
from .response_image_process_args import ResponseImageProcessArgs
from .response_image_process_error import ResponseImageProcessError

__all__ = ["ItemFunctionImageProcess"]
class ItemFunctionImageProcess(BaseModel):
    type: Literal["image_process"]
    action: ResponseImageProcessAction
    arguments: ResponseImageProcessArgs
    status: Literal["in_progress", "completed", "incomplete", "searching", "failed"]
    id: str
    error: Optional[ResponseImageProcessError] = ...


