"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["KnowledgeSearchToolParam"]
class KnowledgeSearchToolParam(TypedDict, total=False):
    type: Required[Literal["knowledge_search"]]
    knowledge_resource_id: Required[str]
    description: Optional[str]
    limit: Optional[int]
    dense_weight: Optional[float]
    doc_filter: Optional[Dict[str, Any]]
    ranking_options: Optional[Dict[str, Any]]
    max_keyword: Optional[int]
    ...


