"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["KnowledgeSearchTool"]
class KnowledgeSearchTool(BaseModel):
    type: Literal["knowledge_search"]
    knowledge_resource_id: str
    description: Optional[str] = ...
    limit: Optional[int] = ...
    dense_weight: Optional[float] = ...
    doc_filter: Optional[Dict[str, Any]] = ...
    ranking_options: Optional[Dict[str, Any]] = ...
    max_keyword: Optional[int] = ...


