"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional, Union
from typing_extensions import Literal, Required, TypeAlias, TypedDict

__all__ = ["Mcp", "McpAllowedTools", "McpAllowedToolsMcpAllowedToolsFilter", "McpRequireApproval", "McpRequireApprovalMcpToolApprovalFilter", "McpRequireApprovalMcpToolApprovalFilterAlways", "McpRequireApprovalMcpToolApprovalFilterNever"]
class McpAllowedToolsMcpAllowedToolsFilter(TypedDict, total=False):
    tool_names: List[str]
    ...


class McpRequireApprovalMcpToolApprovalFilterAlways(TypedDict, total=False):
    tool_names: List[str]
    ...


class McpRequireApprovalMcpToolApprovalFilterNever(TypedDict, total=False):
    tool_names: List[str]
    ...


class McpRequireApprovalMcpToolApprovalFilter(TypedDict, total=False):
    always: McpRequireApprovalMcpToolApprovalFilterAlways
    never: McpRequireApprovalMcpToolApprovalFilterNever
    ...


McpAllowedTools: TypeAlias = Union[List[str], McpAllowedToolsMcpAllowedToolsFilter]
McpRequireApproval: TypeAlias = Union[McpRequireApprovalMcpToolApprovalFilter, Literal["always", "never"]]
class Mcp(TypedDict, total=False):
    server_label: Required[str]
    server_url: Required[str]
    type: Required[Literal["mcp"]]
    allowed_tools: Optional[McpAllowedTools]
    headers: Optional[Dict[str, str]]
    require_approval: Optional[McpRequireApproval]
    server_description: str
    ...


