"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional, Union
from typing_extensions import Literal, TypeAlias
from ..._models import BaseModel

__all__ = ["Mcp", "McpAllowedTools", "McpAllowedToolsMcpAllowedToolsFilter", "McpRequireApproval", "McpRequireApprovalMcpToolApprovalFilter", "McpRequireApprovalMcpToolApprovalFilterAlways", "McpRequireApprovalMcpToolApprovalFilterNever"]
class McpAllowedToolsMcpAllowedToolsFilter(BaseModel):
    tool_names: Optional[List[str]] = ...


class McpRequireApprovalMcpToolApprovalFilterAlways(BaseModel):
    tool_names: Optional[List[str]] = ...


class McpRequireApprovalMcpToolApprovalFilterNever(BaseModel):
    tool_names: Optional[List[str]] = ...


class McpRequireApprovalMcpToolApprovalFilter(BaseModel):
    always: Optional[McpRequireApprovalMcpToolApprovalFilterAlways] = ...
    never: Optional[McpRequireApprovalMcpToolApprovalFilterNever] = ...


McpAllowedTools: TypeAlias = Union[List[str], McpAllowedToolsMcpAllowedToolsFilter, None]
McpRequireApproval: TypeAlias = Union[McpRequireApprovalMcpToolApprovalFilter, Literal["always", "never"], None]
class Mcp(BaseModel):
    server_label: str
    server_url: str
    type: Literal["mcp"]
    allowed_tools: Optional[McpAllowedTools] = ...
    headers: Optional[Dict[str, str]] = ...
    require_approval: Optional[McpRequireApproval] = ...
    server_description: Optional[str] = ...


