"""
This type stub file was generated by pyright.
"""

from typing_extensions import Iterable, Literal, Optional, Required, TypedDict

__all__ = ["McpListTools", "McpListToolsTool", "McpApprovalRequest", "McpApprovalResponse", "McpCall"]
class McpListToolsTool(TypedDict, total=False):
    input_schema: Required[object]
    name: Required[str]
    annotations: Optional[object]
    description: Optional[str]
    ...


class McpListTools(TypedDict, total=False):
    id: Required[str]
    server_label: Required[str]
    tools: Required[Iterable[McpListToolsTool]]
    type: Required[Literal["mcp_list_tools"]]
    error: Optional[str]
    ...


class McpApprovalRequest(TypedDict, total=False):
    id: Required[str]
    arguments: Required[str]
    name: Required[str]
    server_label: Required[str]
    type: Required[Literal["mcp_approval_request"]]
    ...


class McpApprovalResponse(TypedDict, total=False):
    approval_request_id: Required[str]
    approve: Required[bool]
    type: Required[Literal["mcp_approval_response"]]
    id: Optional[str]
    reason: Optional[str]
    ...


class McpCall(TypedDict, total=False):
    id: Required[str]
    arguments: Required[str]
    name: Required[str]
    server_label: Required[str]
    type: Required[Literal["mcp_call"]]
    error: Optional[str]
    output: Optional[str]
    ...


