"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFunctionCallArgumentsDeltaEvent"]
class ResponseFunctionCallArgumentsDeltaEvent(BaseModel):
    delta: str
    item_id: str
    output_index: int
    type: Literal["response.function_call_arguments.delta"]
    ...


