"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from ..._models import BaseModel

__all__ = ["ToolUsage", "ToolUsageDetails"]
class ToolUsage(BaseModel):
    web_search: Optional[int] = ...
    mcp: Optional[int] = ...
    knowledge_search: Optional[int] = ...


class ToolUsageDetails(BaseModel):
    web_search: Dict[str, int]
    mcp: Dict[str, int]
    knowledge_search: Dict[str, int]
    ...


