"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseInputTextParam"]
class ResponseInputTextParam(TypedDict, total=False):
    text: Required[str]
    type: Required[Literal["input_text"]]
    ...


