"""
This type stub file was generated by pyright.
"""

from .response_function_tool_call import ResponseFunctionToolCall

__all__ = ["ResponseFunctionToolCallItem"]
class ResponseFunctionToolCallItem(ResponseFunctionToolCall):
    id: str
    ...


