"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import TypeAlias
from .response_image_process_grounding_args import ResponseImageProcessGroundingArgs
from .response_image_process_point_args import ResponseImageProcessPointArgs
from .response_image_process_rotate_args import ResponseImageProcessRotateArgs
from .response_image_process_zoom_args import ResponseImageProcessZoomArgs

__all__ = ["ResponseImageProcessArgs"]
ResponseImageProcessArgs: TypeAlias = Union[ResponseImageProcessPointArgs, ResponseImageProcessGroundingArgs, ResponseImageProcessRotateArgs, ResponseImageProcessZoomArgs,]
