"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseKnowledgeSearchCallFailedEvent"]
class ResponseKnowledgeSearchCallFailedEvent(BaseModel):
    type: Literal["response.knowledge_search_call.failed"]
    item_id: str
    ...


