"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseKnowledgeSearchItem"]
class ResponseKnowledgeSearchItem(BaseModel):
    type: Literal["knowledge_search_call"]
    queries: List[str]
    knowledge_resource_id: str
    status: Literal["in_progress", "completed", "incomplete", "searching", "failed"]
    id: Optional[str] = ...


