"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .response_image_process_action import ResponseImageProcessAction
from .response_image_process_args import ResponseImageProcessArgs
from .response_image_process_error import ResponseImageProcessError

__all__ = ["ResponseImageProcessCallCompletedEvent"]
class ResponseImageProcessCallCompletedEvent(BaseModel):
    type: Literal["response.image_process_call.completed"]
    item_id: str
    action: ResponseImageProcessAction
    arguments: ResponseImageProcessArgs
    error: Optional[ResponseImageProcessError] = ...


