"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ResponseImageProcessError"]
class ResponseImageProcessError(BaseModel):
    message: str
    ...


