"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import Literal
from ..._models import BaseModel
from .response_item import ResponseItem

__all__ = ["ResponseItemList"]
class ResponseItemList(BaseModel):
    data: List[ResponseItem]
    first_id: str
    has_more: bool
    last_id: str
    object: Literal["list"]
    ...


