"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, TypeAlias
from ..._utils import PropertyInfo
from ..shared.response_format_text import ResponseFormatText
from ..shared.response_format_json_object import ResponseFormatJSONObject

__all__ = ["ResponseFormatTextConfig"]
ResponseFormatTextConfig: TypeAlias = Annotated[Union[ResponseFormatText, ResponseFormatJSONObject], PropertyInfo(discriminator="type"),]
