"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseInputImage"]
class ResponseInputImage(BaseModel):
    detail: Literal["low", "high", "auto"]
    type: Literal["input_image"]
    file_id: Optional[str] = ...
    image_url: Optional[str] = ...


