"""
This type stub file was generated by pyright.
"""

from typing_extensions import List, Literal, Optional
from ..._models import BaseModel

__all__ = ["McpListTools", "McpListToolsTool", "McpApprovalRequest", "McpApprovalResponse", "McpCall"]
class McpListToolsTool(BaseModel):
    input_schema: object
    name: str
    annotations: Optional[object] = ...
    description: Optional[str] = ...


class McpListTools(BaseModel):
    id: str
    server_label: str
    tools: List[McpListToolsTool]
    type: Literal["mcp_list_tools"]
    error: Optional[str] = ...


class McpApprovalRequest(BaseModel):
    id: str
    arguments: str
    name: str
    server_label: str
    type: Literal["mcp_approval_request"]
    ...


class McpApprovalResponse(BaseModel):
    id: str
    approval_request_id: str
    approve: bool
    type: Literal["mcp_approval_response"]
    reason: Optional[str] = ...


class McpCall(BaseModel):
    id: str
    arguments: str
    name: str
    server_label: str
    type: Literal["mcp_call"]
    error: Optional[str] = ...
    output: Optional[str] = ...


