"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseKnowledgeSearchCallCompletedEvent"]
class ResponseKnowledgeSearchCallCompletedEvent(BaseModel):
    type: Literal["response.knowledge_search_call.completed"]
    item_id: str
    ...


