"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel
from .response_output_item import ResponseOutputItem

__all__ = ["ResponseOutputItemDoneEvent"]
class ResponseOutputItemDoneEvent(BaseModel):
    item: ResponseOutputItem
    output_index: int
    type: Literal["response.output_item.done"]
    ...


