"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseReasoningSummaryTextDeltaEvent"]
class ResponseReasoningSummaryTextDeltaEvent(BaseModel):
    delta: str
    item_id: str
    output_index: int
    summary_index: int
    type: Literal["response.reasoning_summary_text.delta"]
    ...


