"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .response_input_message_content_list import ResponseInputMessageContentList

__all__ = ["ResponseInputMessageItem"]
class ResponseInputMessageItem(BaseModel):
    id: str
    content: ResponseInputMessageContentList
    role: Literal["user", "system", "developer"]
    status: Optional[Literal["in_progress", "completed", "incomplete"]] = ...
    type: Optional[Literal["message"]] = ...


