"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel
from .response_output_text import ResponseOutputTextAnnotation

class ResponseOutputTextAnnotationAddedEvent(BaseModel):
    item_id: str
    output_index: int
    type: Literal["response.output_text.annotation.added"]
    content_index: int
    annotation: ResponseOutputTextAnnotation
    ...


