"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseInputVideo"]
class ResponseInputVideo(BaseModel):
    type: Literal["input_video"]
    video_url: str
    file_id: Optional[str] = ...
    fps: Optional[float] = ...


