"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseFunctionToolCallParam"]
class ResponseFunctionToolCallParam(TypedDict, total=False):
    arguments: Required[str]
    call_id: Required[str]
    name: Required[str]
    type: Required[Literal["function_call"]]
    ...


