"""
This type stub file was generated by pyright.
"""

from typing_extensions import TypedDict
from .response_format_text_config_param import ResponseFormatTextConfigParam

__all__ = ["ResponseTextConfigParam"]
class ResponseTextConfigParam(TypedDict, total=False):
    format: ResponseFormatTextConfigParam
    ...


