"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, TypeAlias
from ..._utils import PropertyInfo
from .response_output_message import ResponseOutputMessage
from .response_input_message_item import ResponseInputMessageItem
from .response_function_tool_call_item import ResponseFunctionToolCallItem
from .response_function_tool_call_output_item import ResponseFunctionToolCallOutputItem
from .response_mcp_item import McpApprovalRequest, McpCall, McpListTools

__all__ = ["ResponseItem"]
ResponseItem: TypeAlias = Annotated[Union[ResponseInputMessageItem, ResponseOutputMessage, ResponseFunctionToolCallItem, ResponseFunctionToolCallOutputItem, McpListTools, McpApprovalRequest, McpCall,], PropertyInfo(discriminator="type"),]
