"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel
from typing import Optional

__all__ = ["IncompleteDetails", "ContentFilter"]
class IncompleteDetails(BaseModel):
    reason: str = ...
    content_filter: Optional[str] = ...


class ContentFilter(BaseModel):
    type: str = ...
    details: Optional[str] = ...


