"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from typing_extensions import TypeAlias
from .response_input_audio_param import ResponseInputAudioParam
from .response_input_file_param import ResponseInputFileParam
from .response_input_image_param import ResponseInputImageParam
from .response_input_text_param import ResponseInputTextParam
from .response_input_video_param import ResponseInputVideoParam

__all__ = ["ResponseInputMessageContentListParam", "ResponseInputContentParam"]
ResponseInputContentParam: TypeAlias = Union[ResponseInputTextParam, ResponseInputImageParam, ResponseInputVideoParam, ResponseInputAudioParam, ResponseInputFileParam,]
ResponseInputMessageContentListParam: TypeAlias = List[ResponseInputContentParam]
