"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseMcpListToolsCompletedEvent"]
class ResponseMcpListToolsCompletedEvent(BaseModel):
    item_id: str
    output_index: int
    sequence_number: int
    type: Literal["response.mcp_list_tools.completed"]
    ...


