"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Union
from typing_extensions import Literal, Required, TypeAlias, TypedDict

__all__ = ["ResponseOutputTextParam", "Annotation", "AnnotationFileCitation", "AnnotationURLCitation", "AnnotationFilePath"]
class AnnotationFileCitation(TypedDict, total=False):
    file_id: Required[str]
    index: Required[int]
    type: Required[Literal["file_citation"]]
    ...


class AnnotationURLCitation(TypedDict, total=False):
    end_index: Required[int]
    start_index: Required[int]
    title: Required[str]
    type: Required[Literal["url_citation"]]
    url: Required[str]
    ...


class AnnotationFilePath(TypedDict, total=False):
    file_id: Required[str]
    index: Required[int]
    type: Required[Literal["file_path"]]
    ...


Annotation: TypeAlias = Union[AnnotationFileCitation, AnnotationURLCitation, AnnotationFilePath]
class ResponseOutputTextParam(TypedDict, total=False):
    annotations: Required[Iterable[Annotation]]
    text: Required[str]
    type: Required[Literal["output_text"]]
    ...


