"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseInputFile"]
class ResponseInputFile(BaseModel):
    type: Literal["input_file"]
    file_data: Optional[str] = ...
    file_id: Optional[str] = ...
    file_url: Optional[str] = ...
    filename: Optional[str] = ...


