"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel
from .response_image_process_action import ResponseImageProcessAction
from .response_image_process_args import ResponseImageProcessArgs

__all__ = ["ResponseImageProcessCallProcessingEvent"]
class ResponseImageProcessCallProcessingEvent(BaseModel):
    type: Literal["response.image_process_call.progressing"]
    item_id: str
    action: ResponseImageProcessAction
    arguments: ResponseImageProcessArgs
    ...


