"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseReasoningItemParam", "Summary"]
class Summary(TypedDict, total=False):
    text: Required[str]
    type: Required[Literal["summary_text"]]
    ...


class ResponseReasoningItemParam(TypedDict, total=False):
    summary: Required[Iterable[Summary]]
    type: Required[Literal["reasoning"]]
    ...


