"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseTextDeltaEvent"]
class ResponseTextDeltaEvent(BaseModel):
    content_index: int
    delta: str
    item_id: str
    output_index: int
    type: Literal["response.output_text.delta"]
    ...


