"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseErrorEvent"]
class ResponseErrorEvent(BaseModel):
    code: Optional[str] = ...
    message: str
    param: Optional[str] = ...
    type: Literal["error"]


