"""
This type stub file was generated by pyright.
"""

from typing_extensions import List, Literal, Optional
from ..._models import BaseModel
from .response_output_text_annotation import ResponseOutputTextAnnotation

__all__ = ["ResponseOutputText", "ResponseOutputTextAnnotation"]
class ResponseOutputText(BaseModel):
    text: str
    type: Literal["output_text"]
    annotations: Optional[List[ResponseOutputTextAnnotation]]
    ...


