"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict
from .audio_chunking_strategy_param import AudioChunkingStrategyParam

__all__ = ["ResponseInputAudioParam"]
class ResponseInputAudioParam(TypedDict, total=False):
    type: Required[Literal["input_audio"]]
    chunking_strategy: Optional[AudioChunkingStrategyParam]
    audio_url: Required[str]
    file_id: Optional[str]
    audio_bytes: Optional[bytes]
    ...


