"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ResponseImageProcessPointArgs"]
class ResponseImageProcessPointArgs(BaseModel):
    image_index: int
    points: str
    drawLine: bool
    ...


