"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import TypeAlias
from .response_input_content import ResponseInputContent

__all__ = ["ResponseInputMessageContentList"]
ResponseInputMessageContentList: TypeAlias = List[ResponseInputContent]
