"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseInputFileParam"]
class ResponseInputFileParam(TypedDict, total=False):
    type: Required[Literal["input_file"]]
    file_data: Optional[str]
    file_id: Optional[str]
    file_url: Optional[str]
    filename: Optional[str]
    ...


