"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFunctionToolCall"]
class ResponseFunctionToolCall(BaseModel):
    arguments: str
    call_id: str
    name: str
    type: Literal["function_call"]
    id: Optional[str] = ...
    status: Optional[Literal["in_progress", "completed", "incomplete"]] = ...


