"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel

__all__ = ["ResponseImageProcessAction"]
class ResponseImageProcessAction(BaseModel):
    type: str
    result_image_url: Optional[str] = ...


