"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .audio_chunking_strategy import AudioChunkingStrategy

__all__ = ["ResponseInputAudio"]
class ResponseInputAudio(BaseModel):
    type: Literal["input_audio"]
    chunking_strategy: Optional[AudioChunkingStrategy] = ...
    audio_url: str
    file_id: Optional[str] = ...
    audio_bytes: Optional[bytes] = ...


