"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel
from .response_format_text_config import ResponseFormatTextConfig

__all__ = ["ResponseTextConfig"]
class ResponseTextConfig(BaseModel):
    format: Optional[ResponseFormatTextConfig] = ...


