"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, Literal, TypeAlias
from ..._utils import PropertyInfo
from ..._models import BaseModel
from .response_output_text import ResponseOutputText

__all__ = ["ResponseContentPartAddedEvent", "Part"]
Part: TypeAlias = Annotated[Union[ResponseOutputText], PropertyInfo(discriminator="type")]
class ResponseContentPartAddedEvent(BaseModel):
    content_index: int
    item_id: str
    output_index: int
    part: Part
    type: Literal["response.content_part.added"]
    ...


