"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, TypeAlias
from ..._utils import PropertyInfo
from .response_input_audio import ResponseInputAudio
from .response_input_file import ResponseInputFile
from .response_input_image import ResponseInputImage
from .response_input_text import ResponseInputText
from .response_input_video import ResponseInputVideo

__all__ = ["ResponseInputContent"]
ResponseInputContent: TypeAlias = Annotated[Union[ResponseInputText, ResponseInputImage, ResponseInputVideo, ResponseInputAudio, ResponseInputFile,], PropertyInfo(discriminator="type"),]
