"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFunctionToolCallOutputItem"]
class ResponseFunctionToolCallOutputItem(BaseModel):
    id: str
    call_id: str
    output: str
    type: Literal["function_call_output"]
    status: Optional[Literal["in_progress", "completed", "incomplete"]] = ...


