"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import TypeAlias
from ..shared_params.response_format_text import ResponseFormatText
from ..shared_params.response_format_json_object import ResponseFormatJSONObject

__all__ = ["ResponseFormatTextConfigParam"]
ResponseFormatTextConfigParam: TypeAlias = Union[ResponseFormatText, ResponseFormatJSONObject]
