"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ResponseImageProcessGroundingArgs"]
class ResponseImageProcessGroundingArgs(BaseModel):
    image_index: int
    bbox_str: str
    crop: bool
    ...


