"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from typing_extensions import Literal, Required, TypeAlias, TypedDict
from .easy_input_message_param import EasyInputMessageParam
from .response_function_tool_call_param import ResponseFunctionToolCallParam
from .mcp_input_item_param import McpApprovalRequest, McpApprovalResponse, McpCall, McpListTools

__all__ = ["ResponseInputParam", "ResponseInputItemParam", "FunctionCallOutput"]
class FunctionCallOutput(TypedDict, total=False):
    call_id: Required[str]
    output: Required[str]
    type: Required[Literal["function_call_output"]]
    ...


ResponseInputItemParam: TypeAlias = Union[EasyInputMessageParam, ResponseFunctionToolCallParam, FunctionCallOutput, McpApprovalRequest, McpApprovalResponse, McpListTools, McpCall,]
ResponseInputParam: TypeAlias = List[ResponseInputItemParam]
