"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel
from .response_tool_usage import ToolUsage, ToolUsageDetails

__all__ = ["ResponseUsage", "InputTokensDetails", "OutputTokensDetails"]
class InputTokensDetails(BaseModel):
    cached_tokens: int
    ...


class OutputTokensDetails(BaseModel):
    reasoning_tokens: int
    ...


class ResponseUsage(BaseModel):
    input_tokens: int
    input_tokens_details: InputTokensDetails
    output_tokens: int
    output_tokens_details: OutputTokensDetails
    total_tokens: int
    tool_usage: Optional[ToolUsage]
    tool_usage_details: Optional[ToolUsageDetails]
    ...


