"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ResponseImageProcessZoomArgs"]
class ResponseImageProcessZoomArgs(BaseModel):
    image_index: int
    bbox_str: str
    scale: float
    ...


