"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict
from .response_input_image_pixel_limit_param import ResponseInputImagePixelLimit

__all__ = ["ResponseInputImageParam"]
class ResponseInputImageParam(TypedDict, total=False):
    detail: Required[Literal["low", "high", "auto"]]
    type: Required[Literal["input_image"]]
    image_url: Optional[str]
    file_id: Optional[str]
    image_pixel_limit: Optional[ResponseInputImagePixelLimit]
    ...


