"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseMcpCallCompletedEvent"]
class ResponseMcpCallCompletedEvent(BaseModel):
    item_id: str
    output_index: int
    sequence_number: int
    type: Literal["response.mcp_call.completed"]
    ...


