"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypeAlias

__all__ = ["ResponseIncludable"]
ResponseIncludable: TypeAlias = Literal["message.input_image.image_url",]
