"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from .response import Response
from ..._models import BaseModel

__all__ = ["ResponseIncompleteEvent"]
class ResponseIncompleteEvent(BaseModel):
    response: Response
    type: Literal["response.incomplete"]
    ...


