"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, TypedDict

__all__ = ["ResponseCaching"]
class ResponseCaching(TypedDict, total=False):
    type: Optional[Literal["disabled", "enabled"]]
    prefix: Optional[bool]
    ...


