"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseReasoningSummaryPartDoneEvent", "Part"]
class Part(BaseModel):
    text: str
    type: Literal["summary_text"]
    ...


class ResponseReasoningSummaryPartDoneEvent(BaseModel):
    item_id: str
    output_index: int
    part: Part
    summary_index: int
    type: Literal["response.reasoning_summary_part.done"]
    ...


