"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseWebSearchItem"]
class ResponseWebSearchAction(BaseModel):
    query: str
    type: Literal["search"]
    ...


class ResponseWebSearchItem(BaseModel):
    id: str
    action: Optional[ResponseWebSearchAction] = ...
    type: Literal["web_search_call"]
    status: Optional[Literal["in_progress", "completed", "incomplete"]] = ...


