"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseInputVideoParam"]
class ResponseInputVideoParam(TypedDict, total=False):
    type: Required[Literal["input_video"]]
    video_url: Required[str]
    file_id: Optional[str]
    fps: Optional[float]
    ...


