"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseImageProcessCallInProgressEvent"]
class ResponseImageProcessCallInProgressEvent(BaseModel):
    type: Literal["response.image_process_call.in_progress"]
    item_id: str
    ...


