"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseReasoningItem", "Summary"]
class Summary(BaseModel):
    text: str
    type: Literal["summary_text"]
    ...


class ResponseReasoningItem(BaseModel):
    id: str
    summary: List[Summary]
    type: Literal["reasoning"]
    status: Optional[Literal["in_progress", "completed", "incomplete"]] = ...


