"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseWebSearchCallInProgressEvent"]
class ResponseWebSearchCallInProgressEvent(BaseModel):
    item_id: str
    output_index: int
    type: Literal["response.web_search_call.in_progress"]
    ...


