"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import TypeAlias
from .response_input_text_param import ResponseInputTextParam
from .response_input_image_param import ResponseInputImageParam

__all__ = ["ResponseInputContentParam"]
ResponseInputContentParam: TypeAlias = Union[ResponseInputTextParam, ResponseInputImageParam]
