"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseInputText"]
class ResponseInputText(BaseModel):
    text: str
    type: Literal["input_text"]
    ...


