"""
This type stub file was generated by pyright.
"""

from typing_extensions import Required, TypedDict

__all__ = ["ResponseInputImagePixelLimit"]
class ResponseInputImagePixelLimit(TypedDict, total=False):
    min_pixels: Required[int]
    max_pixels: Required[int]
    ...


