"""
This type stub file was generated by pyright.
"""

from typing import Optional
from ..._models import BaseModel

__all__ = ["ResponsesOutputTextAnnotationCoverImage"]
class ResponsesOutputTextAnnotationCoverImage(BaseModel):
    url: Optional[str] = ...
    width: Optional[int] = ...
    height: Optional[int] = ...


