"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseKnowledgeSearchCallInProgressEvent"]
class ResponseKnowledgeSearchCallInProgressEvent(BaseModel):
    type: Literal["response.knowledge_search_call.in_progress"]
    item_id: str
    ...


