"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseCaching"]
class ResponseCaching(BaseModel):
    type: Optional[Literal["disabled", "enabled"]] = ...
    prefix: Optional[bool] = ...


