"""
This type stub file was generated by pyright.
"""

from typing import List, Union
from typing_extensions import Annotated, Literal, TypeAlias
from ..._utils import PropertyInfo
from ..._models import BaseModel
from .response_output_text import ResponseOutputText

__all__ = ["ResponseOutputMessage", "Content"]
Content: TypeAlias = Annotated[Union[ResponseOutputText], PropertyInfo(discriminator="type")]
class ResponseOutputMessage(BaseModel):
    id: str
    content: List[Content]
    role: Literal["assistant"]
    status: Literal["in_progress", "completed", "incomplete"]
    type: Literal["message"]
    ...


