"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypeAlias

__all__ = ["ResponseStatus"]
ResponseStatus: TypeAlias = Literal["completed", "failed", "in_progress", "incomplete"]
