"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseKnowledgeSearchCallSearchingEvent"]
class ResponseKnowledgeSearchCallSearchingEvent(BaseModel):
    type: Literal["response.knowledge_search_call.searching"]
    item_id: str
    ...


