"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import TypeAlias
from .tool_choice_function_param import ToolChoiceFunctionParam
from .tool_choice_knowledge_search_param import ToolChoiceKnowledgeSearchParam
from .tool_choice_mcp_param import ToolChoiceMcpParam
from .tool_choice_options import ToolChoiceOptions
from .tool_choice_web_search_param import ToolChoiceWebSearchParam

__all__ = ["ToolChoice"]
ToolChoice: TypeAlias = Union[ToolChoiceOptions, ToolChoiceFunctionParam, ToolChoiceMcpParam, ToolChoiceWebSearchParam, ToolChoiceKnowledgeSearchParam,]
