"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseTextDoneEvent"]
class ResponseTextDoneEvent(BaseModel):
    content_index: int
    item_id: str
    output_index: int
    text: str
    type: Literal["response.output_text.done"]
    ...


