"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ResponseImageProcessRotateArgs"]
class ResponseImageProcessRotateArgs(BaseModel):
    image_index: int
    degree: int
    ...


