"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypeAlias

__all__ = ["ToolChoiceOptions"]
ToolChoiceOptions: TypeAlias = Literal["none", "auto", "required"]
