"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ToolChoiceKnowledgeSearch"]
class ToolChoiceKnowledgeSearch(BaseModel):
    type: Literal["knowledge_search"]
    ...


