"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ToolChoiceMcp"]
class ToolChoiceMcp(BaseModel):
    type: Literal["mcp"]
    server_label: str
    name: Optional[str] = ...


