"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ToolChoiceFunctionParam"]
class ToolChoiceFunctionParam(TypedDict, total=False):
    name: Required[str]
    type: Required[Literal["function"]]
    ...


