"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import TypeAlias
from .function_tool_param import FunctionToolParam
from .image_process_tool_param import ImageProcessToolParam
from .knowledge_search_tool_param import KnowledgeSearchToolParam
from .mcp_tool_param import Mcp
from .web_search_tool_param import WebSearchToolParam

__all__ = ["ToolParam"]
ToolParam: TypeAlias = Union[FunctionToolParam, WebSearchToolParam, ImageProcessToolParam, Mcp, KnowledgeSearchToolParam,]
