"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ToolChoiceFunction"]
class ToolChoiceFunction(BaseModel):
    name: str
    type: Literal["function"]
    ...


