"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, TypeAlias
from ..._utils import PropertyInfo
from .function_tool import FunctionTool
from .image_process_tool import ImageProcessTool
from .knowledge_search_tool import KnowledgeSearchTool
from .mcp_tool import Mcp
from .web_search_tool import WebSearchTool

__all__ = ["Tool"]
Tool: TypeAlias = Annotated[Union[FunctionTool, WebSearchTool, ImageProcessTool, Mcp, KnowledgeSearchTool], PropertyInfo(discriminator="type"),]
