"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ToolChoiceKnowledgeSearchParam"]
class ToolChoiceKnowledgeSearchParam(TypedDict, total=False):
    type: Required[Literal["knowledge_search"]]
    ...


