"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["ToolChoiceMcpParam"]
class ToolChoiceMcpParam(TypedDict, total=False):
    type: Required[Literal["mcp"]]
    server_label: Required[str]
    name: Optional[str]
    ...


