"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ToolChoiceWebSearchParam"]
class ToolChoiceWebSearchParam(TypedDict, total=False):
    type: Required[Literal["web_search"]]
    ...


