"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["UserLocation"]
class UserLocation(BaseModel):
    type: Literal["approximate"]
    city: Optional[str]
    country: Optional[str]
    region: Optional[str]
    timezone: Optional[float]
    ...


