"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["UserLocationParam"]
class UserLocationParam(TypedDict, total=False):
    type: Required[Literal["approximate"]]
    city: Optional[str]
    country: Optional[str]
    region: Optional[str]
    timezone: Optional[float]
    ...


