"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .user_location import UserLocation

__all__ = ["WebSearchTool"]
class WebSearchTool(BaseModel):
    type: Literal["web_search"]
    limit: Optional[int] = ...
    user_location: Optional[UserLocation] = ...
    sources: List[Literal["toutiao", "douyin", "moji", "search_engine"]]
    max_keyword: Optional[int] = ...


