"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal, Required, TypedDict
from .user_location_param import UserLocationParam

__all__ = ["WebSearchToolParam"]
class WebSearchToolParam(TypedDict, total=False):
    type: Required[Literal["web_search"]]
    limit: Optional[int]
    user_location: Optional[UserLocationParam]
    sources: Required[List[Literal["toutiao", "douyin", "moji", "search_engine"]]]
    max_keyword: Optional[int]
    ...


