"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, TYPE_CHECKING, Union
from zai.core import BaseAPI
from zai.types.moderation.moderation_completion import Completion
from zai._client import ZaiClient

logger = ...
if TYPE_CHECKING:
	...
class Moderations(BaseAPI):
	"""
	API resource for content moderation operations
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def create(self, *, model: str, input: Union[str, List[str], Dict]) -> Completion:
		"""
		Moderate content for safety and compliance

		Arguments:
			model (str): The moderation model to use
			input (Union[str, List[str], Dict]): Content to moderate
		"""
		...
	


