"""
This type stub file was generated by pyright.
"""

from volcenginesdkarkruntime._models import BaseModel

__all__ = ["ContentGenerationTask"]
class Usage(BaseModel):
    completion_tokens: int
    ...


class Content(BaseModel):
    video_url: str
    last_frame_url: str
    file_url: str
    ...


class ContentGenerationError(BaseModel):
    message: str
    code: str
    ...


class ContentGenerationTask(BaseModel):
    id: str
    model: str
    status: str
    error: ContentGenerationError
    content: Content
    usage: Usage
    subdivisionlevel: str
    fileformat: str
    frames: int
    framespersecond: int
    created_at: int
    updated_at: int
    seed: int
    revised_prompt: str
    ...


