"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Literal, TypedDict

__all__ = ["CreateTaskContentTextParam", "CreateTaskContentImageDataParam", "CreateTaskContentImageParam", "CreateTaskContentParam"]
class CreateTaskContentTextParam(TypedDict):
    type: Literal["text"]
    text: str
    ...


class CreateTaskContentImageDataParam(TypedDict):
    url: str
    ...


class CreateTaskContentImageParam(TypedDict):
    type: Literal["image_url"]
    image_url: CreateTaskContentImageDataParam
    role: str
    ...


CreateTaskContentParam = Union[CreateTaskContentTextParam, CreateTaskContentImageParam]
