"""
This type stub file was generated by pyright.
"""

from typing import List
from .content_generation_task import ContentGenerationTask
from volcenginesdkarkruntime._models import BaseModel

__all__ = ["ListContentGenerationTasksResponse"]
class Content(BaseModel):
    video_url: str
    ...


class Usage(BaseModel):
    completion_tokens: int
    ...


class ListContentGenerationTasksResponse(BaseModel):
    total: int
    items: List[ContentGenerationTask]
    ...


