"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Iterable, Optional, Union
from typing_extensions import Literal
from ..._types import Body, Headers, Query
from ..._utils._utils import async_with_sts_token, with_sts_token
from ..._resource import AsyncAPIResource, SyncAPIResource
from ..._compat import cached_property
from ..._streaming import AsyncStream, Stream
from ...types.responses.response_create_params import ToolChoice
from ...types.responses.response import Response
from ...types.responses.tool_param import ToolParam
from ...types.responses.response_input_param import ResponseInputParam
from ...types.responses.response_stream_event import ResponseStreamEvent
from ...types.responses.response_text_config_param import ResponseTextConfigParam
from ...types.responses.response_caching_param import ResponseCaching
from ...types.shared_params import Reasoning
from volcenginesdkarkruntime.types.shared_params.thinking import Thinking

__all__ = ["Responses", "AsyncResponses"]
RESPONSES_MULTIMODAL_CONTENT_DATA_KEYS = ...
FILE_PATH_SCHEME = ...
class Responses(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ResponsesWithRawResponse:
        ...
    
    @cached_property
    def with_streaming_response(self) -> ResponsesWithStreamingResponse:
        ...
    
    @with_sts_token
    def create(self, *, input: Union[str, ResponseInputParam], model: str, instructions: Optional[str] | None = ..., max_output_tokens: Optional[int] | None = ..., parallel_tool_calls: Optional[bool] | None = ..., previous_response_id: Optional[str] | None = ..., thinking: Optional[Thinking] | None = ..., store: Optional[bool] | None = ..., caching: Optional[ResponseCaching] | None = ..., stream: Optional[Literal[False]] | Literal[True] | None = ..., temperature: Optional[float] | None = ..., text: ResponseTextConfigParam | None = ..., tool_choice: ToolChoice | None = ..., tools: Iterable[ToolParam] | None = ..., top_p: Optional[float] | None = ..., max_tool_calls: Optional[int] | None = ..., expire_at: Optional[int] | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | None = ..., reasoning: Optional[Reasoning] | None = ...) -> Response | Stream[ResponseStreamEvent]:
        ...
    
    def retrieve(self, response_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> Response:
        ...
    
    def delete(self, response_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> None:
        ...
    


class AsyncResponses(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncResponsesWithRawResponse:
        ...
    
    @cached_property
    def with_streaming_response(self) -> AsyncResponsesWithStreamingResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, input: Union[str, ResponseInputParam], model: str, instructions: Optional[str] | None = ..., max_output_tokens: Optional[int] | None = ..., parallel_tool_calls: Optional[bool] | None = ..., previous_response_id: Optional[str] | None = ..., thinking: Optional[Thinking] | None = ..., store: Optional[bool] | None = ..., caching: Optional[ResponseCaching] | None = ..., stream: Optional[Literal[False]] | Literal[True] | None = ..., temperature: Optional[float] | None = ..., text: ResponseTextConfigParam | None = ..., tool_choice: ToolChoice | None = ..., tools: Iterable[ToolParam] | None = ..., top_p: Optional[float] | None = ..., max_tool_calls: Optional[int] | None = ..., expire_at: Optional[int] | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | None = ..., reasoning: Optional[Reasoning] | None = ...) -> Response | AsyncStream[ResponseStreamEvent]:
        ...
    
    async def retrieve(self, response_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> Response:
        ...
    
    async def delete(self, response_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> None:
        ...
    


class ResponsesWithRawResponse:
    def __init__(self, responses: Responses) -> None:
        ...
    


class AsyncResponsesWithRawResponse:
    def __init__(self, responses: AsyncResponses) -> None:
        ...
    


class ResponsesWithStreamingResponse:
    def __init__(self, responses: Responses) -> None:
        ...
    


class AsyncResponsesWithStreamingResponse:
    def __init__(self, responses: AsyncResponses) -> None:
        ...
    


