"""
This type stub file was generated by pyright.
"""

import httpx
from functools import cached_property
from typing import Mapping, TYPE_CHECKING, Union
from httpx import Timeout
from typing_extensions import override
from zai.api_resource.agents import Agents
from zai.api_resource.assistant import Assistant
from zai.api_resource.audio import Audio
from zai.api_resource.batch import Batches
from zai.api_resource.chat import Chat
from zai.api_resource.embeddings import Embeddings
from zai.api_resource.files import Files
from zai.api_resource.images import Images
from zai.api_resource.moderations import Moderations
from zai.api_resource.tools import Tools
from zai.api_resource.videos import Videos
from zai.api_resource.voice import Voice
from zai.api_resource.web_search import WebSearchApi
from zai.api_resource.web_reader import WebReaderApi
from zai.api_resource.file_parser import FileParser
from zai.api_resource.ocr import HandwritingOCR
from .core import HttpClient, NotGiven

if TYPE_CHECKING:
    ...
class BaseClient(HttpClient):
    """
    Main client for interacting with the ZAI API

    Attributes:
        chat (Chat): Chat completions API resource
        api_key (str): API key for authentication
        _disable_token_cache (bool): Whether to disable token caching
        source_channel (str): Source channel identifier
    """
    chat: Chat
    api_key: str
    base_url: str
    disable_token_cache: bool = ...
    source_channel: str
    def __init__(self, *, api_key: str | None = ..., base_url: str | httpx.URL | None = ..., timeout: Union[float, Timeout, None, NotGiven] = ..., max_retries: int = ..., http_client: httpx.Client | None = ..., custom_headers: Mapping[str, str] | None = ..., disable_token_cache: bool = ..., _strict_response_validation: bool = ..., source_channel: str | None = ...) -> None:
        """
        Initialize the ZAI client

        Arguments:
            api_key (str | None): API key for authentication.
                                    If None, will try to get from ZAI_API_KEY environment variable.
            base_url (str | httpx.URL | None): Base URL for the API.
                                    If None, will try to get from ZAI_BASE_URL environment variable
            timeout (Union[float, Timeout, None, NotGiven]): Request timeout configuration
            max_retries (int): Maximum number of retries for failed requests
            http_client (httpx.Client | None): Custom HTTP client to use
            custom_headers (Mapping[str, str] | None): Additional headers to include in requests
            disable_token_cache (bool): Whether to disable JWT token caching
            _strict_response_validation (bool): Whether to enable strict response validation
            source_channel (str | None): Source channel identifier
        """
        ...
    
    @property
    def default_base_url(self):
        ...
    
    @cached_property
    def chat(self) -> Chat:
        ...
    
    @cached_property
    def assistant(self) -> Assistant:
        ...
    
    @cached_property
    def agents(self) -> Agents:
        ...
    
    @cached_property
    def embeddings(self) -> Embeddings:
        ...
    
    @cached_property
    def batches(self) -> Batches:
        ...
    
    @cached_property
    def tools(self) -> Tools:
        ...
    
    @cached_property
    def web_search(self) -> WebSearchApi:
        ...
    
    @cached_property
    def web_reader(self) -> WebReaderApi:
        ...
    
    @cached_property
    def files(self) -> Files:
        ...
    
    @cached_property
    def images(self) -> Images:
        ...
    
    @cached_property
    def audio(self) -> Audio:
        ...
    
    @cached_property
    def videos(self) -> Videos:
        ...
    
    @cached_property
    def moderations(self) -> Moderations:
        ...
    
    @cached_property
    def voice(self) -> Voice:
        ...
    
    @cached_property
    def file_parser(self) -> FileParser:
        ...
    
    @cached_property
    def ocr(self) -> HandwritingOCR:
        ...
    
    @property
    @override
    def auth_headers(self) -> dict[str, str]:
        ...
    
    def __del__(self) -> None:
        ...
    


class ZaiClient(BaseClient):
    @property
    def default_base_url(self): # -> Literal['https://api.z.ai/api/paas/v4']:
        ...
    
    @property
    @override
    def auth_headers(self) -> dict[str, str]:
        ...
    


class ZhipuAiClient(BaseClient):
    @property
    def default_base_url(self): # -> Literal['https://open.bigmodel.cn/api/paas/v4']:
        ...
    


