"""
This type stub file was generated by pyright.
"""

import json
from typing import Optional
from pymilvus.orm.schema import CollectionSchema
from .constants import BulkFileType

logger = ...
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj: object): # -> Any:
        ...
    


def to_raw_type(obj: dict): # -> dict[Any, Any]:
    ...

class Buffer:
    def __init__(self, schema: CollectionSchema, file_type: BulkFileType = ..., config: Optional[dict] = ...) -> None:
        ...
    
    @property
    def row_count(self) -> int:
        ...
    
    def append_row(self, row: dict): # -> None:
        ...
    
    def persist(self, local_path: str, **kwargs) -> list:
        ...
    


