"""
This type stub file was generated by pyright.
"""

import requests
from typing import List, Optional, Union

logger = ...
def bulk_import(url: str, collection_name: str, db_name: str = ..., files: Optional[List[List[str]]] = ..., object_url: str = ..., object_urls: Optional[List[List[str]]] = ..., cluster_id: str = ..., api_key: str = ..., access_key: str = ..., secret_key: str = ..., token: str = ..., stage_name: str = ..., data_paths: [List[List[str]]] = ..., verify: Optional[Union[bool, str]] = ..., cert: Optional[Union[str, tuple]] = ..., **kwargs) -> requests.Response:
    """call bulkinsert restful interface to import files

    Args:
        url (str): url of the server
        collection_name (str): name of the target collection
        db_name (str): name of target database
        partition_name (str): name of the target partition
        files (list of list of str): The files that contain the data to import.
             A sub-list contains a single JSON or Parquet file, or a set of Numpy files.
        api_key (str): API key to authenticate your requests

        cluster_id (str): id of a milvus instance(cloud)
        object_url (str): The object URL of the object to import(cloud), use `object_urls` instead.
        object_urls (list of list of str): The object urls that contain the data to import.
             A sub-list contains a single object url
        access_key (str): access key to access the object storage(cloud)
        secret_key (str): secret key to access the object storage(cloud)
        token (str): access token to access the object storage(cloud)

        stage_name (str): name of the stage to import(cloud)
        data_paths (list of list of str): The paths of files that contain the data to import(cloud)
        verify (bool, str, optional): Either a boolean, to verify the server's TLS certificate
             or a string, which must be server's certificate path. Defaults to `True`.
        cert (str, tuple, optional): if String, path to ssl client cert file.
                                     if Tuple, ('cert', 'key') pair.

    Returns:
        response of the restful interface

    Examples:
        >>> # 1. Import multiple files into an open-source Milvus instance
        >>> bulk_import(
        ...    url="http://127.0.0.1:19530",
        ...    api_key="username:password",
        ...    db_name="",
        ...    collection_name="my_collection",
        ...    partition_name="", # If Collection not enable partitionKey, can be specified.
        ...    files=[
        ...        ["parquet-folder/1.parquet"],
        ...        ["parquet-folder-2/1.parquet"]
        ...    ]
        ... )

        >>> # 2. Import multiple files or folders from object storage into a Zilliz Cloud instance
        >>> bulk_import(
        ...    url="https://api.cloud.zilliz.com", # If regions in China, it is: https://api.cloud.zilliz.com.cn
        ...    api_key="YOUR_API_KEY",
        ...    cluster_id="in0x-xxx",
        ...    db_name="", # Only For Dedicated deployments: this parameter can be specified.
        ...    collection_name="my_collection",
        ...    partition_name="", # If Collection not enable partitionKey, can be specified.
        ...    object_urls=[
        ...        ["s3://bucket-name/parquet-folder-1/1.parquet"],
        ...        ["s3://bucket-name/parquet-folder-2/1.parquet"],
        ...        ["s3://bucket-name/parquet-folder-3/"]
        ...    ],
        ...    access_key="your-access-key",
        ...    secret_key="your-secret-key",
        ...    token="your-token" # for short-term credentials, also include `token`
        ... )

        >>> # 3. Import multiple files or folders from a Zilliz Stage into a Zilliz Cloud instance
        >>> bulk_import(
        ...     url="https://api.cloud.zilliz.com", # If regions in China, it is: https://api.cloud.zilliz.com.cn
        ...     api_key="YOUR_API_KEY",
        ...     cluster_id="in0x-xxx",
        ...     db_name="", # Only For Dedicated deployments: this parameter can be specified.
        ...     collection_name="my_collection",
        ...     partition_name="", # If Collection not enable partitionKey, can be specified.
        ...     stage_name="my_stage",
        ...     data_paths=[
        ...         ["parquet-folder/1.parquet"],
        ...         ["parquet-folder-2/"]
        ...     ]
        ... )
    """
    ...

def get_import_progress(url: str, job_id: str, cluster_id: str = ..., api_key: str = ..., verify: Optional[Union[bool, str]] = ..., cert: Optional[Union[str, tuple]] = ..., **kwargs) -> requests.Response:
    """get job progress

    Args:
        url (str): url of the server
        job_id (str): a job id
        cluster_id (str): id of a milvus instance(for cloud)
        api_key (str): API key to authenticate your requests.
        verify (bool, str, optional): Either a boolean, to verify the server's TLS certificate
             or a string, which must be server's certificate path. Defaults to `True`.
        cert (str, tuple, optional): if String, path to ssl client cert file.
                                     if Tuple, ('cert', 'key') pair.

    Returns:
        response of the restful interface
    """
    ...

def list_import_jobs(url: str, collection_name: str = ..., db_name: str = ..., cluster_id: str = ..., api_key: str = ..., page_size: int = ..., current_page: int = ..., verify: Optional[Union[bool, str]] = ..., cert: Optional[Union[str, tuple]] = ..., **kwargs) -> requests.Response:
    """list jobs in a cluster

    Args:
        url (str): url of the server
        collection_name (str): name of the target collection
        cluster_id (str): id of a milvus instance(for cloud)
        api_key (str): API key to authenticate your requests.
        page_size (int): pagination size
        current_page (int): pagination
        verify (bool, str, optional): Either a boolean, to verify the server's TLS certificate
             or a string, which must be server's certificate path. Defaults to `True`.
        cert (str, tuple, optional): if String, path to ssl client cert file.
                                     if Tuple, ('cert', 'key') pair.

    Returns:
        response of the restful interface
    """
    ...

