"""
This type stub file was generated by pyright.
"""

def float_vector_validator(x: object, dim: int): # -> list[Any] | Any:
    ...

def binary_vector_validator(x: object, dim: int): # -> Any | object:
    ...

def float16_vector_validator(x: object, dim: int, is_bfloat: bool): # -> bytes:
    ...

def int8_vector_validator(x: object, dim: int): # -> list[Any] | Any:
    ...

def sparse_vector_validator(x: object): # -> dict[Any, Any]:
    ...

def struct_validator(x: object, max_cap: int): # -> list[Any]:
    ...

