"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from ...core import BaseModel

__all__ = ["AudioSpeechChunk", "AudioError", "AudioSpeechChoice", "AudioSpeechDelta"]
class AudioSpeechDelta(BaseModel):
    content: Optional[str] = ...
    role: Optional[str] = ...


class AudioSpeechChoice(BaseModel):
    delta: AudioSpeechDelta
    finish_reason: Optional[str] = ...
    index: int


class AudioError(BaseModel):
    code: Optional[str] = ...
    message: Optional[str] = ...


class AudioSpeechChunk(BaseModel):
    choices: List[AudioSpeechChoice]
    request_id: Optional[str] = ...
    created: Optional[int] = ...
    error: Optional[AudioError] = ...


