"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from typing import Optional

__all__ = ["CompletionUsage", "PromptTokensDetails"]
class PromptTokensDetails(BaseModel):
    cached_tokens: int
    provisioned_tokens: Optional[int] = ...


class CompletionTokensDetails(BaseModel):
    reasoning_tokens: Optional[int] = ...
    provisioned_tokens: Optional[int] = ...


class CompletionUsage(BaseModel):
    completion_tokens: int
    prompt_tokens: int
    total_tokens: int
    prompt_tokens_details: Optional[PromptTokensDetails] = ...
    completion_tokens_details: Optional[CompletionTokensDetails] = ...


