"""
This type stub file was generated by pyright.
"""

from typing import Dict, List
from .completion_usage import CompletionUsage
from .._models import BaseModel

__all__ = ["CreateClassificationResponse"]
class LabelLogprobosValue(BaseModel):
    tokens: List[str]
    token_logprobs: List[float]
    ...


class CreateClassificationResponse(BaseModel):
    label: str
    label_logprobos: Dict[str, LabelLogprobosValue]
    usage: CompletionUsage
    ...


