"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import Literal
from .._models import BaseModel
from .embedding import Embedding

__all__ = ["CreateEmbeddingResponse", "Usage"]
class Usage(BaseModel):
    prompt_tokens: int
    total_tokens: int
    ...


class CreateEmbeddingResponse(BaseModel):
    id: str
    created: int
    data: List[Embedding]
    model: str
    object: Literal["list"]
    usage: Usage
    ...


