"""
This type stub file was generated by pyright.
"""

from typing import List
from .._models import BaseModel
from typing_extensions import Literal

__all__ = ["CreateTokenizationResponse", "Tokenization"]
class Tokenization(BaseModel):
    index: int
    object: Literal["tokenization"]
    total_tokens: int
    token_ids: List[int]
    offset_mapping: List[List[int]]
    ...


class CreateTokenizationResponse(BaseModel):
    id: str
    created: int
    model: str
    object: Literal["list"]
    data: List[Tokenization]
    ...


