"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import Literal
from .._models import BaseModel

__all__ = ["Embedding"]
class Embedding(BaseModel):
    embedding: List[float]
    index: int
    object: Literal["embedding"]
    ...


