"""
This type stub file was generated by pyright.
"""

from .file_purpose import FilePurpose as FilePurpose
from typing_extensions import Literal, TypedDict

__all__ = ["FileListParams"]
class FileListParams(TypedDict, total=False):
    after: str
    limit: int
    order: Literal["asc", "desc"]
    purpose: FilePurpose
    ...


