"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from .._models import BaseModel

__all__ = ["FileObject"]
class Error(BaseModel):
    code: str
    message: str
    param: Optional[str] = ...
    type: Optional[str] = ...


class FileObject(BaseModel):
    id: str
    bytes: int
    created_at: int
    expire_at: int
    filename: str
    object: Literal["file"]
    purpose: Literal["user_data",]
    status: Literal["processing", "active", "failed"]
    error: Optional[Error] = ...
    mime_type: Optional[str] = ...
    preprocess_configs: Optional[dict] = ...


