"""
This type stub file was generated by pyright.
"""

import datetime
from typing_extensions import Required, TypedDict
from typing import Optional
from .._types import FileTypes
from .file_purpose import FilePurpose

__all__ = ["FileCreateParams", "PreprocessConfigs"]
class FileCreateParams(TypedDict, total=False):
    file: Required[FileTypes]
    purpose: Required[FilePurpose]
    expire_at: datetime.datetime
    preprocess_configs: Optional[PreprocessConfigs]
    ...


class Video(TypedDict, total=False):
    """The video configs of the file."""
    fps: float
    ...


class PreprocessConfigs(TypedDict, total=False):
    """The preprocess configs of the file."""
    video: Optional[Video]
    ...


