"""
This type stub file was generated by pyright.
"""

import pydantic
from typing import Any, TypeVar
from typing_extensions import TypeGuard

_T = TypeVar("_T")
def to_strict_json_schema(model: type[pydantic.BaseModel] | pydantic.TypeAdapter[Any]) -> dict[str, Any]:
    ...

def resolve_ref(*, root: dict[str, object], ref: str) -> object:
    ...

def is_basemodel_type(typ: type) -> TypeGuard[type[pydantic.BaseModel]]:
    ...

def is_dataclass_like_type(typ: type) -> bool:
    """Returns True if the given type likely used `@pydantic.dataclass`"""
    ...

def is_dict(obj: object) -> TypeGuard[dict[str, object]]:
    ...

def has_more_than_n_keys(obj: dict[str, object], n: int) -> bool:
    ...

