"""
This type stub file was generated by pyright.
"""

import pydantic
from typing import Any, Dict
from ..types.chat import ChatCompletionToolParam
from ..types.shared_params import FunctionDefinition

class PydanticFunctionTool(Dict[str, Any]):
    """Dictionary wrapper so we can pass the given base model
    throughout the entire request stack without having to special
    case it.
    """
    model: type[pydantic.BaseModel]
    def __init__(self, defn: FunctionDefinition, model: type[pydantic.BaseModel]) -> None:
        ...
    
    def cast(self) -> FunctionDefinition:
        ...
    


def pydantic_function_tool(model: type[pydantic.BaseModel], *, name: str | None = ..., description: str | None = ...) -> ChatCompletionToolParam:
    ...

