"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Optional, Union
from typing_extensions import Literal, Required, TypedDict
from .chat_completion_message_tool_call_param import ChatCompletionMessageToolCallParam
from .chat_completion_content_part_param import ChatCompletionContentPartParam

__all__ = ["ChatCompletionAssistantMessageParam", "FunctionCall"]
class FunctionCall(TypedDict, total=False):
    arguments: Required[str]
    name: Required[str]
    ...


class ChatCompletionAssistantMessageParam(TypedDict, total=False):
    role: Required[Literal["assistant"]]
    content: Optional[Union[str, Iterable[ChatCompletionContentPartParam]]]
    name: Optional[str]
    function_call: FunctionCall
    tool_calls: Iterable[ChatCompletionMessageToolCallParam]
    ...


