"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict
from ...types import shared_params

__all__ = ["ChatCompletionToolParam"]
class ChatCompletionToolParam(TypedDict, total=False):
    function: Required[shared_params.FunctionDefinition]
    type: Required[Literal["function"]]
    ...


