"""
This type stub file was generated by pyright.
"""

from typing import Iterable, Optional, Union
from typing_extensions import Literal, Required, TypedDict
from .chat_completion_content_part_param import ChatCompletionContentPartParam

__all__ = ["ChatCompletionUserMessageParam"]
class ChatCompletionUserMessageParam(TypedDict, total=False):
    content: Required[Union[str, Iterable[ChatCompletionContentPartParam]]]
    role: Required[Literal["user"]]
    name: Optional[str]
    ...


