"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ChatCompletionContentPartVideoParam", "VideoURL"]
class VideoURL(TypedDict, total=False):
    url: Required[str]
    fps: float
    ...


class ChatCompletionContentPartVideoParam(TypedDict, total=False):
    video_url: Required[VideoURL]
    type: Required[Literal["video_url"]]
    ...


