"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from ..._models import BaseModel

__all__ = ["ChatCompletionTokenLogprob", "TopLogprob"]
class TopLogprob(BaseModel):
    token: str
    bytes: Optional[List[int]] = ...
    logprob: float


class ChatCompletionTokenLogprob(BaseModel):
    token: str
    bytes: Optional[List[int]] = ...
    logprob: float
    top_logprobs: List[TopLogprob]


