"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel
from ..completion_usage import CompletionUsage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob

__all__ = ["ChatCompletionChunk", "Choice", "ChoiceDelta", "ChoiceDeltaFunctionCall", "ChoiceDeltaToolCall", "ChoiceDeltaToolCallFunction", "ChoiceLogprobs"]
class ChoiceDeltaFunctionCall(BaseModel):
    arguments: Optional[str] = ...
    name: Optional[str] = ...


class ChoiceDeltaToolCallFunction(BaseModel):
    arguments: Optional[str] = ...
    name: Optional[str] = ...


class ChoiceDeltaToolCall(BaseModel):
    index: int
    id: Optional[str] = ...
    function: Optional[ChoiceDeltaToolCallFunction] = ...
    type: Optional[Literal["function"]] = ...


class ChoiceDelta(BaseModel):
    content: Optional[str] = ...
    function_call: Optional[ChoiceDeltaFunctionCall] = ...
    role: Optional[Literal["system", "user", "assistant", "tool"]] = ...
    tool_calls: Optional[List[ChoiceDeltaToolCall]] = ...
    reasoning_content: Optional[str] = ...


class ChoiceLogprobs(BaseModel):
    content: Optional[List[ChatCompletionTokenLogprob]] = ...


class Choice(BaseModel):
    delta: ChoiceDelta
    finish_reason: Optional[Literal["stop", "length", "tool_calls", "content_filter", "function_call"]] = ...
    moderation_hit_type: Optional[Literal["violence", "severe_violation"]] = ...
    index: int
    logprobs: Optional[ChoiceLogprobs] = ...


class ChatCompletionChunk(BaseModel):
    id: str
    choices: List[Choice]
    created: int
    model: str
    service_tier: Optional[Literal["auto", "default"]]
    object: Literal["chat.completion.chunk"]
    usage: Optional[CompletionUsage] = ...


