"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ChatCompletionNamedToolChoiceParam", "Function"]
class Function(TypedDict, total=False):
    name: Required[str]
    ...


class ChatCompletionNamedToolChoiceParam(TypedDict, total=False):
    function: Required[Function]
    type: Required[Literal["function"]]
    ...


