"""
This type stub file was generated by pyright.
"""

from typing_extensions import Required, TypedDict

__all__ = ["ChatCompletionFunctionCallOptionParam"]
class ChatCompletionFunctionCallOptionParam(TypedDict, total=False):
    name: Required[str]
    ...


