"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ChatCompletionMessageToolCall", "Function"]
class Function(BaseModel):
    arguments: str
    name: str
    ...


class ChatCompletionMessageToolCall(BaseModel):
    id: str
    function: Function
    type: Literal["function"]
    ...


