"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from ..._models import BaseModel
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from .chat_completion_audio import ChatCompletionAudio

__all__ = ["ChatCompletionMessage", "FunctionCall"]
class FunctionCall(BaseModel):
    arguments: str
    name: str
    ...


class ChatCompletionMessage(BaseModel):
    content: Optional[str] = ...
    role: Literal["assistant"]
    function_call: Optional[FunctionCall] = ...
    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = ...
    audio: Optional[ChatCompletionAudio] = ...
    reasoning_content: Optional[str] = ...


