"""
This type stub file was generated by pyright.
"""

from typing_extensions import TypedDict

__all__ = ["ChatCompletionStreamOptionsParam"]
class ChatCompletionStreamOptionsParam(TypedDict, total=False):
    include_usage: bool
    chunk_include_usage: bool
    ...


