"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from typing_extensions import Literal
from .chat_completion_message import ChatCompletionMessage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob
from ..completion_usage import CompletionUsage
from ..._models import BaseModel

__all__ = ["ChatCompletion", "Choice", "ChoiceLogprobs"]
class ChoiceLogprobs(BaseModel):
    content: Optional[List[ChatCompletionTokenLogprob]] = ...


class Choice(BaseModel):
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    moderation_hit_type: Optional[Literal["violence", "severe_violation"]] = ...
    index: int
    logprobs: Optional[ChoiceLogprobs] = ...
    message: ChatCompletionMessage


class ChatCompletion(BaseModel):
    id: str
    choices: List[Choice]
    created: int
    model: str
    service_tier: Optional[Literal["auto", "default"]]
    object: Literal["chat.completion"]
    usage: Optional[CompletionUsage] = ...


