"""
This type stub file was generated by pyright.
"""

from ..._models import BaseModel

__all__ = ["ChatCompletionAudio"]
class ChatCompletionAudio(BaseModel):
    id: str
    data: str
    expires_at: int
    transcript: str
    ...


