"""
This type stub file was generated by pyright.
"""

from typing import Dict, Iterable, List, Optional, Union
from typing_extensions import Literal, Required, TypeAlias, TypedDict
from ...types import shared_params
from ..shared_params.response_format_text import ResponseFormatText
from ..shared_params.response_format_json_object import ResponseFormatJSONObject
from ..shared_params.response_format_json_schema import ResponseFormatJSONSchema
from .chat_completion_tool_param import ChatCompletionToolParam
from .chat_completion_message_param import ChatCompletionMessageParam
from .chat_completion_tool_choice_option_param import ChatCompletionToolChoiceOptionParam
from .chat_completion_function_call_option_param import ChatCompletionFunctionCallOptionParam

__all__ = ["CompletionCreateParamsBase", "FunctionCall", "Function", "ResponseFormat", "CompletionCreateParamsNonStreaming", "CompletionCreateParamsStreaming"]
class CompletionCreateParamsBase(TypedDict, total=False):
    messages: Required[Iterable[ChatCompletionMessageParam]]
    model: Required[str]
    frequency_penalty: Optional[float]
    function_call: FunctionCall
    functions: Iterable[Function]
    logit_bias: Optional[Dict[str, int]]
    logprobs: Optional[bool]
    max_tokens: Optional[int]
    n: Optional[int]
    presence_penalty: Optional[float]
    response_format: ResponseFormat
    seed: Optional[int]
    stop: Union[Optional[str], List[str]]
    temperature: Optional[float]
    tool_choice: ChatCompletionToolChoiceOptionParam
    tools: Iterable[ChatCompletionToolParam]
    top_logprobs: Optional[int]
    top_p: Optional[float]
    user: str
    ...


FunctionCall = Union[Literal["none", "auto"], ChatCompletionFunctionCallOptionParam]
class Function(TypedDict, total=False):
    name: Required[str]
    description: str
    parameters: shared_params.FunctionParameters
    ...


ResponseFormat: TypeAlias = Union[ResponseFormatText, ResponseFormatJSONSchema, ResponseFormatJSONObject]
class CompletionCreateParamsNonStreaming(CompletionCreateParamsBase):
    stream: Optional[Literal[False]]
    ...


class CompletionCreateParamsStreaming(CompletionCreateParamsBase):
    stream: Required[Literal[True]]
    ...


CompletionCreateParams = Union[CompletionCreateParamsNonStreaming, CompletionCreateParamsStreaming]
class Thinking(TypedDict, total=False):
    type: Literal["enabled", "disabled", "auto"]
    ...


