"""
This type stub file was generated by pyright.
"""

from typing import Generic, List, Optional, TypeVar
from ..._models import GenericModel
from .chat_completion import ChatCompletion, Choice
from .chat_completion_message import ChatCompletionMessage
from .parsed_function_tool_call import ParsedFunctionToolCall

__all__ = ["ParsedChatCompletion", "ParsedChoice"]
ContentType = TypeVar("ContentType")
class ParsedChatCompletionMessage(ChatCompletionMessage, GenericModel, Generic[ContentType]):
    parsed: Optional[ContentType] = ...
    tool_calls: Optional[List[ParsedFunctionToolCall]] = ...


class ParsedChoice(Choice, GenericModel, Generic[ContentType]):
    message: ParsedChatCompletionMessage[ContentType]
    ...


class ParsedChatCompletion(ChatCompletion, GenericModel, Generic[ContentType]):
    choices: List[ParsedChoice[ContentType]]
    ...


