"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall, Function

__all__ = ["ParsedFunctionToolCall", "ParsedFunction"]
class ParsedFunction(Function):
    parsed_arguments: Optional[object] = ...


class ParsedFunctionToolCall(ChatCompletionMessageToolCall):
    function: ParsedFunction
    ...


