"""
This type stub file was generated by pyright.
"""

from typing_extensions import TypeAlias
from ....types.chat import ParsedChatCompletion, ParsedChatCompletionMessage, ParsedChoice

ParsedChatCompletionSnapshot: TypeAlias = ParsedChatCompletion[object]
ParsedChatCompletionMessageSnapshot: TypeAlias = ParsedChatCompletionMessage[object]
ParsedChoiceSnapshot: TypeAlias = ParsedChoice[object]
