"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Dict, Iterable, List, Optional, Union
from typing_extensions import Literal
from ..._types import Body, Headers, Query
from ..._utils._utils import async_with_sts_token, with_sts_token
from ..._resource import AsyncAPIResource, SyncAPIResource
from ..._compat import cached_property
from ..._streaming import AsyncStream, Stream
from ...types.context import ContextChatCompletion, ContextChatCompletionChunk
from ...types.chat import ChatCompletionMessageParam, ChatCompletionStreamOptionsParam, ChatCompletionToolChoiceOptionParam, ChatCompletionToolParam, completion_create_params

__all__ = ["Completions", "AsyncCompletions"]
class Completions(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> CompletionsWithRawResponse:
        ...
    
    @cached_property
    def with_streaming_response(self) -> CompletionsWithStreamingResponse:
        ...
    
    @with_sts_token
    def create(self, *, context_id: str, messages: Iterable[ChatCompletionMessageParam], model: str, frequency_penalty: Optional[float] | None = ..., function_call: completion_create_params.FunctionCall | None = ..., logit_bias: Optional[Dict[str, int]] | None = ..., logprobs: Optional[bool] | None = ..., max_tokens: Optional[int] | None = ..., presence_penalty: Optional[float] | None = ..., stop: Union[Optional[str], List[str]] | None = ..., stream: Optional[Literal[False]] | Literal[True] | None = ..., stream_options: Optional[ChatCompletionStreamOptionsParam] | None = ..., temperature: Optional[float] | None = ..., tools: Iterable[ChatCompletionToolParam] | None = ..., top_logprobs: Optional[int] | None = ..., top_p: Optional[float] | None = ..., repetition_penalty: Optional[float] | None = ..., n: Optional[int] | None = ..., tool_choice: ChatCompletionToolChoiceOptionParam | None = ..., response_format: completion_create_params.ResponseFormat | None = ..., user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContextChatCompletion | Stream[ContextChatCompletionChunk]:
        ...
    


class AsyncCompletions(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncCompletionsWithRawResponse:
        ...
    
    @cached_property
    def with_streaming_response(self) -> AsyncCompletionsWithStreamingResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, context_id: str, messages: Iterable[ChatCompletionMessageParam], model: str, frequency_penalty: Optional[float] | None = ..., function_call: completion_create_params.FunctionCall | None = ..., logit_bias: Optional[Dict[str, int]] | None = ..., logprobs: Optional[bool] | None = ..., max_tokens: Optional[int] | None = ..., presence_penalty: Optional[float] | None = ..., stop: Union[Optional[str], List[str]] | None = ..., stream: Optional[Literal[False]] | Literal[True] | None = ..., stream_options: Optional[ChatCompletionStreamOptionsParam] | None = ..., temperature: Optional[float] | None = ..., tools: Iterable[ChatCompletionToolParam] | None = ..., top_logprobs: Optional[int] | None = ..., top_p: Optional[float] | None = ..., user: str | None = ..., repetition_penalty: Optional[float] | None = ..., n: Optional[int] | None = ..., tool_choice: ChatCompletionToolChoiceOptionParam | None = ..., response_format: completion_create_params.ResponseFormat | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ContextChatCompletion | AsyncStream[ContextChatCompletionChunk]:
        ...
    


class CompletionsWithRawResponse:
    def __init__(self, completions: Completions) -> None:
        ...
    


class AsyncCompletionsWithRawResponse:
    def __init__(self, completions: AsyncCompletions) -> None:
        ...
    


class CompletionsWithStreamingResponse:
    def __init__(self, completions: Completions) -> None:
        ...
    


class AsyncCompletionsWithStreamingResponse:
    def __init__(self, completions: AsyncCompletions) -> None:
        ...
    


