"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Iterable, Optional
from typing_extensions import Literal
from ..._types import Body, Headers, Query
from .completions import AsyncCompletions, Completions
from ..._compat import cached_property
from ..._resource import AsyncAPIResource, SyncAPIResource
from ..._utils._utils import async_with_sts_token, with_sts_token
from ...types.context import CreateContextResponse
from ...types.context.context_create_params import TTLTypes, TruncationStrategy
from ...types.chat import ChatCompletionMessageParam

__all__ = ["Context", "AsyncContext"]
class Context(SyncAPIResource):
    @cached_property
    def completions(self) -> Completions:
        ...
    
    @with_sts_token
    def create(self, *, model: str, messages: Iterable[ChatCompletionMessageParam], ttl: Optional[TTLTypes] | None = ..., mode: Literal["session", "common_prefix"] = ..., truncation_strategy: Optional[TruncationStrategy] | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateContextResponse:
        ...
    


class AsyncContext(AsyncAPIResource):
    @cached_property
    def completions(self) -> AsyncCompletions:
        ...
    
    @async_with_sts_token
    async def create(self, *, model: str, mode: Literal["session", "common_prefix"] = ..., messages: Iterable[ChatCompletionMessageParam], ttl: Optional[TTLTypes] | None = ..., truncation_strategy: Optional[TruncationStrategy] | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateContextResponse:
        ...
    


