"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Required, TypedDict
from ...types import shared_params

__all__ = ["FunctionDefinition"]
class FunctionDefinition(TypedDict, total=False):
    name: Required[str]
    description: str
    parameters: shared_params.FunctionParameters
    strict: Optional[bool]
    ...


