"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseFormatJSONObject"]
class ResponseFormatJSONObject(TypedDict, total=False):
    type: Required[Literal["json_object"]]
    ...


