"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseFormatText"]
class ResponseFormatText(TypedDict, total=False):
    type: Required[Literal["text"]]
    ...


