"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Literal, Required, TypedDict

__all__ = ["ResponseFormatJSONSchema", "JSONSchema"]
class JSONSchema(TypedDict, total=False):
    name: Required[str]
    description: str
    schema: Dict[str, object]
    strict: Optional[bool]
    ...


class ResponseFormatJSONSchema(TypedDict, total=False):
    json_schema: Required[JSONSchema]
    type: Required[Literal["json_schema"]]
    ...


