"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypedDict

__all__ = ["Thinking"]
class Thinking(TypedDict, total=False):
    type: Literal["enabled", "disabled", "auto"]
    ...


