"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Dict, Literal, Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.core.pagination import SyncCursorPage
from zai.types.batch import Batch
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Batches(BaseAPI):
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def create(self, *, completion_window: str | None = ..., endpoint: Literal['/v1/chat/completions', '/v1/embeddings'], input_file_id: str, metadata: Optional[Dict[str, str]] | NotGiven = ..., auto_delete_input_file: bool = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> Batch:
		...
	
	def retrieve(self, batch_id: str, *, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> Batch:
		"""
		Retrieves a batch.

		Args:
		  extra_headers: Send extra headers

		  extra_body: Add additional JSON properties to the request

		  timeout: Override the client-level default timeout for this request, in seconds
		"""
		...
	
	def list(self, *, after: str | NotGiven = ..., limit: int | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> SyncCursorPage[Batch]:
		"""List your organization's batches.

		Args:
		  after: A cursor for use in pagination.

		    `after` is an object ID that defines your place
		      in the list. For instance, if you make a list request and receive 100 objects,
		      ending with obj_foo, your subsequent call can include after=obj_foo in order to
		      fetch the next page of the list.

		  limit: A limit on the number of objects to be returned. Limit can range between 1 and
		      100, and the default is 20.

		  extra_headers: Send extra headers

		  extra_body: Add additional JSON properties to the request

		  timeout: Override the client-level default timeout for this request, in seconds
		"""
		...
	
	def cancel(self, batch_id: str, *, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> Batch:
		"""
		Cancels an in-progress batch.

		Args:
		  batch_id: The ID of the batch to cancel.
		  extra_headers: Send extra headers

		  extra_body: Add additional JSON properties to the request

		  timeout: Override the client-level default timeout for this request, in seconds

		"""
		...
	


