"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.web_reader.web_reader_resp import WebReaderResult
from zai._client import ZaiClient

if TYPE_CHECKING:
    ...
class WebReaderApi(BaseAPI):
    def __init__(self, client: ZaiClient) -> None:
        ...
    
    def web_reader(self, *, url: str, request_id: Optional[str] | NotGiven = ..., user_id: Optional[str] | NotGiven = ..., timeout: Optional[str] | NotGiven = ..., no_cache: Optional[bool] | NotGiven = ..., return_format: Optional[str] | NotGiven = ..., retain_images: Optional[bool] | NotGiven = ..., no_gfm: Optional[bool] | NotGiven = ..., keep_img_data_url: Optional[bool] | NotGiven = ..., with_images_summary: Optional[bool] | NotGiven = ..., with_links_summary: Optional[bool] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout_override: float | httpx.Timeout | None | NotGiven = ...) -> WebReaderResult:
        ...
    


