"""
This type stub file was generated by pyright.
"""

import httpx
from typing import TYPE_CHECKING
from typing_extensions import Literal
from zai.core import BaseAPI, Body, FileTypes, Headers, NotGiven
from zai.types.ocr.handwriting_ocr_resp import HandwritingOCRResp
from zai._client import ZaiClient

if TYPE_CHECKING:
    ...
__all__ = ["HandwritingOCR"]
class HandwritingOCR(BaseAPI):
    def __init__(self, client: ZaiClient) -> None:
        ...
    
    def handwriting_ocr(self, *, file: FileTypes, tool_type: Literal["hand_write"], language_type: str = ..., probability: bool = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> HandwritingOCRResp:
        ...
    


