"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypedDict
from zai.core import FileTypes

__all__ = ["FileParserCreateParams", "FileParserDownloadParams"]
class FileParserCreateParams(TypedDict):
    file: FileTypes
    file_type: str
    tool_type: Literal["lite", "expert", "prime"]
    ...


class FileParserDownloadParams(TypedDict):
    task_id: str
    format_type: Literal["text", "download_link"]
    ...


class FileParserSyncParams(TypedDict):
    file: FileTypes
    file_type: str
    tool_type: Literal["prime-sync"]
    ...


