"""
This type stub file was generated by pyright.
"""

from zai.core import BaseModel

__all__ = ["FileParserTaskCreateResp", "FileParsingDownloadResp"]
class FileParserTaskCreateResp(BaseModel):
    task_id: str
    message: str
    success: bool
    ...


class FileParsingDownloadResp(BaseModel):
    task_id: str
    message: str
    status: bool
    content: str
    parsing_result_url: str
    ...


