"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from zai.core import BaseModel

__all__ = ["HandwritingOCRResp"]
class Location(BaseModel):
    left: int
    top: int
    width: int
    height: int
    ...


class Probability(BaseModel):
    average: float
    variance: float
    min: float
    ...


class WordsResult(BaseModel):
    location: Location
    words: str
    probability: Probability
    ...


class HandwritingOCRResp(BaseModel):
    task_id: str
    message: str
    status: str
    words_result_num: int
    words_result: Optional[List[WordsResult]] = ...


