"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal, TypedDict
from zai.core import FileTypes

__all__ = ["HandwritingOCRParams"]
class HandwritingOCRParams(TypedDict, total=False):
    file: FileTypes
    tool_type: Literal["hand_write"]
    language_type: str
    probability: bool
    ...


