"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.image import ImagesResponded
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Images(BaseAPI):
	"""
	API resource for image generation operations
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def generations(self, *, prompt: str, model: str | NotGiven = ..., n: Optional[int] | NotGiven = ..., quality: Optional[str] | NotGiven = ..., response_format: Optional[str] | NotGiven = ..., size: Optional[str] | NotGiven = ..., style: Optional[str] | NotGiven = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., user: str | NotGiven = ..., request_id: Optional[str] | NotGiven = ..., user_id: Optional[str] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., disable_strict_validation: Optional[bool] | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ..., watermark_enabled: Optional[bool] | NotGiven = ...) -> ImagesResponded:
		"""
		Generate images from text prompts

		Arguments:
			prompt (str): Text description of the desired image
			model (str): The model to use for image generation
			n (Optional[int]): Number of images to generate
			quality (Optional[str]): Quality level of the generated images
			response_format (Optional[str]): Format of the response
			size (Optional[str]): Size of the generated images
			style (Optional[str]): Style of the generated images
			sensitive_word_check (Optional[SensitiveWordCheckRequest]): Sensitive word check configuration
			user (str): User identifier
			request_id (Optional[str]): Unique identifier for the request
			user_id (Optional[str]): User identifier
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			disable_strict_validation (Optional[bool]): Whether to disable strict validation
			timeout (float | httpx.Timeout): Request timeout
			watermark_enabled (Optional[bool]): Whether to enable watermark on generated images
		"""
		...
	


