"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Optional, TYPE_CHECKING
from typing_extensions import Literal
from zai.core import BaseAPI, Body, Headers, NotGiven, StreamResponse
from zai.types.assistant import AssistantCompletion, assistant_create_params
from zai.types.assistant.assistant_conversation_resp import ConversationUsageListResp
from zai.types.assistant.assistant_support_resp import AssistantSupportResp
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
__all__ = ['Assistant']
class Assistant(BaseAPI):
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def conversation(self, assistant_id: str, messages: List[assistant_create_params.ConversationMessage], model: str = ..., *, stream: Optional[Literal[False]] | Literal[True] | NotGiven = ..., conversation_id: Optional[str] = ..., attachments: Optional[List[assistant_create_params.AssistantAttachments]] = ..., metadata: dict | None = ..., request_id: str = ..., user_id: str = ..., extra_parameters: Optional[assistant_create_params.ExtraParameters] = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> AssistantCompletion | StreamResponse[AssistantCompletion]:
		...
	
	def query_support(self, *, assistant_id_list: List[str] = ..., request_id: str = ..., user_id: str = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> AssistantSupportResp:
		...
	
	def query_conversation_usage(self, assistant_id: str, page: int = ..., page_size: int = ..., *, request_id: str = ..., user_id: str = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> ConversationUsageListResp:
		...
	


