"""
This type stub file was generated by pyright.
"""

from typing import Iterable
from typing_extensions import TypeGuard, TypeVar
from ..._types import NotGiven
from ...types.chat import ChatCompletion, ChatCompletionMessage, ChatCompletionToolParam, ParsedChatCompletion, ParsedChatCompletionMessage, ParsedFunction, completion_create_params
from ...types.chat.completion_create_params import ResponseFormat as ResponseFormatParam
from ...types.chat.chat_completion_message_tool_call import Function

ResponseFormatT = TypeVar("ResponseFormatT", default=None)
_default_response_format: None = ...
def validate_input_tools(tools: Iterable[ChatCompletionToolParam] | NotGiven = ...) -> None:
    ...

def parse_chat_completion(*, response_format: type[ResponseFormatT] | completion_create_params.ResponseFormat | NotGiven, input_tools: Iterable[ChatCompletionToolParam] | NotGiven, chat_completion: ChatCompletion | ParsedChatCompletion[object]) -> ParsedChatCompletion[ResponseFormatT]:
    ...

def get_input_tool_by_name(*, input_tools: list[ChatCompletionToolParam], name: str) -> ChatCompletionToolParam | None:
    ...

def parse_function_tool_arguments(*, input_tools: list[ChatCompletionToolParam], function: Function | ParsedFunction) -> object:
    ...

def maybe_parse_content(*, response_format: type[ResponseFormatT] | ResponseFormatParam | NotGiven, message: ChatCompletionMessage | ParsedChatCompletionMessage[object]) -> ResponseFormatT | None:
    ...

def solve_response_format_t(response_format: type[ResponseFormatT] | ResponseFormatParam | NotGiven) -> type[ResponseFormatT]:
    """Return the runtime type for the given response format.

    If no response format is given, or if we won't auto-parse the response format
    then we default to `None`.
    """
    ...

def has_parseable_input(*, response_format: type | ResponseFormatParam | NotGiven, input_tools: Iterable[ChatCompletionToolParam] | NotGiven = ...) -> bool:
    ...

def has_rich_response_format(response_format: type[ResponseFormatT] | ResponseFormatParam | NotGiven) -> TypeGuard[type[ResponseFormatT]]:
    ...

def is_response_format_param(response_format: object) -> TypeGuard[ResponseFormatParam]:
    ...

def is_parseable_tool(input_tool: ChatCompletionToolParam) -> bool:
    ...

def type_to_response_format_param(response_format: type | completion_create_params.ResponseFormat | NotGiven) -> ResponseFormatParam | NotGiven:
    ...

