"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFormatJSONSchema", "JSONSchema"]
class JSONSchema(BaseModel):
    name: str
    description: Optional[str] = ...
    schema_: Optional[Dict[str, object]] = ...
    strict: Optional[bool] = ...


class ResponseFormatJSONSchema(BaseModel):
    json_schema: JSONSchema
    type: Literal["json_schema"]
    ...


