"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFormatJSONObject"]
class ResponseFormatJSONObject(BaseModel):
    type: Literal["json_object"]
    ...


