"""
This type stub file was generated by pyright.
"""

from typing_extensions import Literal
from ..._models import BaseModel

__all__ = ["ResponseFormatText"]
class ResponseFormatText(BaseModel):
    type: Literal["text"]
    ...


