"""
This type stub file was generated by pyright.
"""

from typing import Optional
from typing_extensions import Literal
from pydantic import BaseModel

__all__ = ["Thinking"]
class Thinking(BaseModel):
    type: Optional[Literal["enabled", "disabled", "auto"]]
    ...


