"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List
from .._compat import cached_property
from .._resource import AsyncAPIResource, SyncAPIResource
from .._types import Body, Headers, Query
from .._utils._utils import async_with_sts_token, with_sts_token
from ..types.create_classification_response import CreateClassificationResponse

__all__ = ["Classification", "AsyncClassification"]
class Classification(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> ClassificationWithRawResponse:
        ...
    
    @with_sts_token
    def create(self, *, query: str, model: str, labels: List[str], user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateClassificationResponse:
        ...
    


class AsyncClassification(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncClassificationWithRawResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, query: str, model: str, labels: List[str], user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateClassificationResponse:
        ...
    


class ClassificationWithRawResponse:
    def __init__(self, classification: Classification) -> None:
        ...
    


class AsyncClassificationWithRawResponse:
    def __init__(self, classification: AsyncClassification) -> None:
        ...
    


