"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Union
from typing_extensions import Literal
from .._types import Body, Headers, Query
from .._compat import cached_property
from .._resource import AsyncAPIResource, SyncAPIResource
from .._utils._utils import async_with_sts_token, with_sts_token
from ..types.create_embedding_response import CreateEmbeddingResponse

__all__ = ["Embeddings", "AsyncEmbeddings"]
class Embeddings(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> EmbeddingsWithRawResponse:
        ...
    
    @with_sts_token
    def create(self, *, input: Union[str, List[str]], model: str, encoding_format: Literal["float", "base64"] = ..., user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateEmbeddingResponse:
        ...
    


class AsyncEmbeddings(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncEmbeddingsWithRawResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, input: Union[str, List[str]], model: str, encoding_format: Literal["float", "base64"] = ..., user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateEmbeddingResponse:
        ...
    


class EmbeddingsWithRawResponse:
    def __init__(self, embeddings: Embeddings) -> None:
        ...
    


class AsyncEmbeddingsWithRawResponse:
    def __init__(self, embeddings: AsyncEmbeddings) -> None:
        ...
    


