"""
This type stub file was generated by pyright.
"""

def with_e2e_encryption(func): # -> Callable[..., ChatCompletion | Stream[ChatCompletionChunk] | Any]:
    ...

def async_with_e2e_encryption(func): # -> Callable[..., CoroutineType[Any, Any, ChatCompletion | AsyncStream[ChatCompletionChunk] | Any]]:
    ...

