"""
This type stub file was generated by pyright.
"""

import datetime
import httpx
from typing_extensions import Literal
from ..types import FilePurpose, PreprocessConfigs
from .._types import Body, FileTypes, Headers, Query
from .._compat import cached_property
from .._resource import AsyncAPIResource, SyncAPIResource
from ..pagination import AsyncCursorPage, SyncCursorPage
from .._base_client import AsyncPaginator
from ..types.file_object import FileObject
from ..types.file_deleted import FileDeleted

__all__ = ["Files", "AsyncFiles"]
class Files(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> FilesWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/openai/openai-python#accessing-raw-response-data-eg-headers
        """
        ...
    
    @cached_property
    def with_streaming_response(self) -> FilesWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/openai/openai-python#with_streaming_response
        """
        ...
    
    def create(self, *, file: FileTypes, purpose: FilePurpose, expires_at: datetime.datetime | int | None = ..., preprocess_configs: PreprocessConfigs | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileObject:
        """Upload a file that can be used across various endpoints.

        Individual files can be up to 512 MB.

        Args:
          file: The File object (not file name) to be uploaded.

          purpose: The intended purpose of the uploaded file. Only `user_data` is supported.

          expires_at: The expiration time for a file in Unix timestamp format. By default, files expires after 7 days.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def retrieve(self, file_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileObject:
        """
        Returns information about a specific file.

        Args:
          file_id: The ID of the file to use for this request.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def list(self, *, after: str | None = ..., limit: int | None = ..., order: Literal["asc", "desc"] | None = ..., purpose: FilePurpose | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> SyncCursorPage[FileObject]:
        """Returns a list of files.

        Args:
          after: A cursor for use in pagination.

        `after` is an object ID that defines your place
              in the list. For instance, if you make a list request and receive 100 objects,
              ending with obj_foo, your subsequent call can include after=obj_foo in order to
              fetch the next page of the list.

          limit: A limit on the number of objects to be returned. Limit can range between 1 and
              1000, and the default is 100

          order: Sort order by the `created_at` timestamp of the objects. `asc` for ascending
              order and `desc` for descending order.

          purpose: Only return files with the given purpose.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def delete(self, file_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileDeleted:
        """
        Delete a file and remove it from all vector stores.

        Args:
          file_id: The ID of the file to use for this request.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def wait_for_processing(self, id: str, *, poll_interval: float = ..., max_wait_seconds: float = ...) -> FileObject:
        """Waits for the given file to be processed, default timeout is 10 mins."""
        ...
    


class AsyncFiles(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncFilesWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.
        """
        ...
    
    @cached_property
    def with_streaming_response(self) -> AsyncFilesWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.
        """
        ...
    
    async def create(self, *, file: FileTypes, purpose: FilePurpose, expire_at: int | None = ..., preprocess_configs: PreprocessConfigs | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileObject:
        """Upload a file that can be used across various endpoints.

        Individual files can be up to 512 MB.

        Args:
          file: The File object (not file name) to be uploaded.

          purpose: The intended purpose of the uploaded file.

          expire_at: The Unix timestamp in seconds after which the file will be deleted. Defaults to 7 days.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    async def retrieve(self, file_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileObject:
        """
        Returns information about a specific file.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    def list(self, *, after: str | None = ..., limit: int | None = ..., order: Literal["asc", "desc"] | None = ..., purpose: FilePurpose | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> AsyncPaginator[FileObject, AsyncCursorPage[FileObject]]:
        """Returns a list of files.

        Args:
          after: A cursor for use in pagination.

        `after` is an object ID that defines your place
              in the list. For instance, if you make a list request and receive 100 objects,
              ending with obj_foo, your subsequent call can include after=obj_foo in order to
              fetch the next page of the list.

          limit: A limit on the number of objects to be returned. Limit can range between 1 and
              10,000, and the default is 10,000.

          order: Sort order by the `created_at` timestamp of the objects. `asc` for ascending
              order and `desc` for descending order.

          purpose: Only return files with the given purpose.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    async def delete(self, file_id: str, *, extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> FileDeleted:
        """
        Delete a file and remove it from all vector stores.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        ...
    
    async def wait_for_processing(self, id: str, *, poll_interval: float = ..., max_wait_seconds: float = ...) -> FileObject:
        """Waits for the given file to be processed, default timeout is 10 mins."""
        ...
    


class FilesWithRawResponse:
    def __init__(self, files: Files) -> None:
        ...
    


class AsyncFilesWithRawResponse:
    def __init__(self, files: AsyncFiles) -> None:
        ...
    


class FilesWithStreamingResponse:
    def __init__(self, files: Files) -> None:
        ...
    


class AsyncFilesWithStreamingResponse:
    def __init__(self, files: AsyncFiles) -> None:
        ...
    


