"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List
from typing_extensions import Literal
from .._types import Body, Headers, Query
from .._compat import cached_property
from .._resource import AsyncAPIResource, SyncAPIResource
from .._utils._utils import async_with_sts_token, with_sts_token
from ..types.multimodal_embedding import EmbeddingInputParam, MultimodalEmbeddingResponse, SparseEmbeddingInput

__all__ = ["MultimodalEmbeddings", "AsyncMultimodalEmbeddings"]
class MultimodalEmbeddings(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> MultimodalEmbeddingsWithRawResponse:
        ...
    
    @with_sts_token
    def create(self, *, input: List[EmbeddingInputParam], model: str, encoding_format: Literal["float", "base64"] = ..., dimensions: int | None = ..., sparse_embedding: SparseEmbeddingInput | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> MultimodalEmbeddingResponse:
        ...
    


class AsyncMultimodalEmbeddings(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncMultimodalEmbeddingsWithRawResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, input: List[EmbeddingInputParam], model: str, encoding_format: Literal["float", "base64"] = ..., dimensions: int | None = ..., sparse_embedding: SparseEmbeddingInput | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> MultimodalEmbeddingResponse:
        ...
    


class MultimodalEmbeddingsWithRawResponse:
    def __init__(self, embeddings: MultimodalEmbeddings) -> None:
        ...
    


class AsyncMultimodalEmbeddingsWithRawResponse:
    def __init__(self, embeddings: AsyncMultimodalEmbeddings) -> None:
        ...
    


