"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Union
from .._types import Body, Headers, Query
from .._compat import cached_property
from .._resource import AsyncAPIResource, SyncAPIResource
from .._utils._utils import async_with_sts_token, with_sts_token
from ..types.create_tokenization_response import CreateTokenizationResponse

__all__ = ["Tokenization", "AsyncTokenization"]
class Tokenization(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> TokenizationWithRawResponse:
        ...
    
    @with_sts_token
    def create(self, *, text: Union[str, List[str]], model: str, user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateTokenizationResponse:
        ...
    


class AsyncTokenization(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncTokenizationWithRawResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, text: Union[str, List[str]], model: str, user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> CreateTokenizationResponse:
        ...
    


class TokenizationWithRawResponse:
    def __init__(self, tokenization: Tokenization) -> None:
        ...
    


class AsyncTokenizationWithRawResponse:
    def __init__(self, tokenization: AsyncTokenization) -> None:
        ...
    


