"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Optional, TYPE_CHECKING, Union
from typing_extensions import Literal
from zai.core import BaseAPI, Body, Headers, NotGiven, StreamResponse
from zai.types.agents.agents_completion import AgentsCompletion
from zai.types.agents.agents_completion_chunk import AgentsCompletionChunk
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from zai._client import ZaiClient

logger = ...
if TYPE_CHECKING:
	...
class Agents(BaseAPI):
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def invoke(self, agent_id: Optional[str] | NotGiven = ..., request_id: Optional[str] | NotGiven = ..., stream: Optional[Literal[False]] | Literal[True] | NotGiven = ..., messages: Union[str, List[str], List[int], object, None] | NotGiven = ..., user_id: Optional[str] | NotGiven = ..., custom_variables: object = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> AgentsCompletion | StreamResponse[AgentsCompletionChunk]:
		...
	
	def async_result(self, agent_id: Optional[str] | NotGiven = ..., async_id: Optional[str] | NotGiven = ..., conversation_id: Optional[str] | NotGiven = ..., custom_variables: object = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> AgentsCompletion:
		...
	


