"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Optional, TYPE_CHECKING, Union
from typing_extensions import Literal
from zai.core import BaseAPI, Body, Headers, NotGiven, StreamResponse
from zai.types.tools import WebSearch, WebSearchChunk
from zai._client import ZaiClient

logger = ...
if TYPE_CHECKING:
	...
class Tools(BaseAPI):
	"""
	API resource for tools functionality.

	Provides access to various tool operations including web search.
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def web_search(self, *, model: str, request_id: Optional[str] | NotGiven = ..., stream: Optional[Literal[False]] | Literal[True] | NotGiven = ..., messages: Union[str, List[str], List[int], object, None], scope: Optional[str] | NotGiven = ..., location: Optional[str] | NotGiven = ..., recent_days: Optional[int] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> WebSearch | StreamResponse[WebSearchChunk]:
		"""
		Perform web search using AI models

		Arguments:
			model (str): The model to use for web search
			request_id (Optional[str]): Unique identifier for the request
			stream (Optional[Literal[False]] | Literal[True]): Whether to stream the response
			messages (Union[str, List[str], List[int], object, None]): Search query or messages
			scope (Optional[str]): Search scope or domain
			location (Optional[str]): Geographic location for search
			recent_days (Optional[int]): Number of recent days to search within
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
		"""
		...
	


