"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from zai.core import BaseAPI, cached_property
from .async_completions import AsyncCompletions
from .completions import Completions

if TYPE_CHECKING:
	...
class Chat(BaseAPI):
	"""
	API resource for chat operations.

	Provides access to chat completions and async completions.
	"""
	@cached_property
	def completions(self) -> Completions:
		...
	
	@cached_property
	def asyncCompletions(self) -> AsyncCompletions:
		...
	


