"""
This type stub file was generated by pyright.
"""

from .completions import AsyncCompletions, Completions
from ..._compat import cached_property
from ..._resource import AsyncAPIResource, SyncAPIResource

__all__ = ["BatchChat", "AsyncBatchChat"]
class BatchChat(SyncAPIResource):
    @cached_property
    def completions(self) -> Completions:
        ...
    


class AsyncBatchChat(AsyncAPIResource):
    @cached_property
    def completions(self) -> AsyncCompletions:
        ...
    


