"""
This type stub file was generated by pyright.
"""

from volcenginesdkarkruntime._models import BaseModel

__all__ = ["ImageGenGeneratingEvent"]
class Error(BaseModel):
    message: str
    code: str
    ...


class ImageGenGeneratingEvent(BaseModel):
    type: str
    model: str
    url: str
    b64_json: str
    size: str
    error: Error
    image_index: int
    created_at: int
    ...


