"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from volcenginesdkarkruntime._models import BaseModel

__all__ = ["OptimizePromptOptions", "SequentialImageGenerationOptions", "ImagesResponse"]
class OptimizePromptOptions(BaseModel):
    thinking: Optional[str] = ...
    mode: Optional[str] = ...


class SequentialImageGenerationOptions(BaseModel):
    max_images: Optional[int] = ...


class Usage(BaseModel):
    generated_images: int
    ...


class Image(BaseModel):
    url: str
    b64_json: str
    size: str
    ...


class Error(BaseModel):
    message: str
    code: str
    ...


class ImagesResponse(BaseModel):
    model: str
    data: List[Image]
    error: Error
    usage: Usage
    created_at: int
    ...


