"""
This type stub file was generated by pyright.
"""

from volcenginesdkarkruntime._models import BaseModel

__all__ = ["ImageGenCompletedEvent"]
class Usage(BaseModel):
    generated_images: int
    output_tokens: int
    total_tokens: int
    ...


class Error(BaseModel):
    message: str
    code: str
    ...


class ImageGenCompletedEvent(BaseModel):
    type: str
    model: str
    error: Error
    usage: Usage
    created_at: int
    ...


