"""
This type stub file was generated by pyright.
"""

from typing import Union
from typing_extensions import Annotated, TypeAlias
from volcenginesdkarkruntime._utils import PropertyInfo
from .image_gen_completed_event import ImageGenCompletedEvent
from .image_gen_generating_event import ImageGenGeneratingEvent

__all__ = ["ImageGenStreamEvent"]
ImageGenStreamEvent: TypeAlias = Annotated[Union[ImageGenGeneratingEvent, ImageGenCompletedEvent], PropertyInfo(discriminator="type"),]
