"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import Literal
from zai.core import BaseModel

class CodeInterpreterToolOutput(BaseModel):
	"""Code tool output result"""
	type: str
	logs: str
	error_msg: str
	...


class CodeInterpreter(BaseModel):
	"""Code interpreter"""
	input: str
	outputs: List[CodeInterpreterToolOutput]
	...


class CodeInterpreterToolBlock(BaseModel):
	"""Code tool block"""
	code_interpreter: CodeInterpreter
	type: Literal['code_interpreter']
	...


