"""
This type stub file was generated by pyright.
"""

import logging
import httpx
from datetime import datetime
from typing import Any, Awaitable, Callable, Optional, TypeVar
from ..._utils._model_breaker import ModelBreaker

log: logging.Logger = ...
def get_request_last_time(client: httpx.Client, timeout: Optional[Any] = ...) -> datetime:
    ...

R = TypeVar("R")
def with_batch_retry(deadline: datetime, breaker: ModelBreaker, func: Callable[..., R], *args, **kwargs) -> R:
    ...

async def async_with_batch_retry(deadline: datetime, breaker: ModelBreaker, func: Callable[..., Awaitable[R]], *args, **kwargs) -> R:
    ...

