"""
This type stub file was generated by pyright.
"""

from ..._compat import cached_property
from ..._resource import AsyncAPIResource, SyncAPIResource
from .chat import AsyncChat, Chat
from .embeddings import AsyncEmbeddings, Embeddings
from .multimodal_embeddings import AsyncMultimodalEmbeddings, MultimodalEmbeddings

__all__ = ["Batch", "AsyncBatch"]
class Batch(SyncAPIResource):
    @cached_property
    def chat(self) -> Chat:
        ...
    
    @cached_property
    def embeddings(self) -> Embeddings:
        ...
    
    @cached_property
    def multimodal_embeddings(self) -> MultimodalEmbeddings:
        ...
    


class AsyncBatch(AsyncAPIResource):
    @cached_property
    def chat(self) -> AsyncChat:
        ...
    
    @cached_property
    def embeddings(self) -> AsyncEmbeddings:
        ...
    
    @cached_property
    def multimodal_embeddings(self) -> AsyncMultimodalEmbeddings:
        ...
    


