"""
This type stub file was generated by pyright.
"""

class _QuerySet:
    def __init__(self) -> None:
        ...
    
    def add(self, item: int) -> None:
        ...
    
    def remove(self, item: int) -> None:
        ...
    
    def query(self, item: int) -> int:
        ...
    


class ModelBreaker:
    def __init__(self) -> None:
        ...
    
    def reset(self, duration: float) -> None:
        ...
    
    def wait(self) -> None:
        ...
    
    async def asyncwait(self) -> None:
        ...
    


