"""
This type stub file was generated by pyright.
"""

from typing import Any
from typing_extensions import AsyncIterator, Iterator

def consume_sync_iterator(iterator: Iterator[Any]) -> None:
    ...

async def consume_async_iterator(iterator: AsyncIterator[Any]) -> None:
    ...

