"""
This type stub file was generated by pyright.
"""

from ._transform import PropertyInfo as PropertyInfo, async_maybe_transform as async_maybe_transform, async_transform as async_transform, maybe_transform as maybe_transform, transform as transform
from ._typing import extract_type_arg as extract_type_arg, extract_type_var_from_base as extract_type_var_from_base, is_annotated_type as is_annotated_type, is_iterable_type as is_iterable_type, is_list_type as is_list_type, is_required_type as is_required_type, is_union_type as is_union_type, strip_annotated_type as strip_annotated_type
from ._utils import coerce_boolean as coerce_boolean, coerce_float as coerce_float, coerce_integer as coerce_integer, deepcopy_minimal as deepcopy_minimal, drop_prefix_image_data as drop_prefix_image_data, extract_files as extract_files, file_from_path as file_from_path, flatten as flatten, get_async_library as get_async_library, get_required_header as get_required_header, is_dict as is_dict, is_given as is_given, is_iterable as is_iterable, is_list as is_list, is_mapping as is_mapping, is_mapping_t as is_mapping_t, is_sequence as is_sequence, is_sequence_t as is_sequence_t, is_tuple as is_tuple, is_tuple_t as is_tuple_t, maybe_coerce_boolean as maybe_coerce_boolean, maybe_coerce_float as maybe_coerce_float, maybe_coerce_integer as maybe_coerce_integer, parse_date as parse_date, parse_datetime as parse_datetime, remove_notgiven_indict as remove_notgiven_indict, removeprefix as removeprefix, removesuffix as removesuffix, required_args as required_args, strip_not_given as strip_not_given

