"""
This type stub file was generated by pyright.
"""

def is_annotated_type(typ: type) -> bool:
	...

def is_list_type(typ: type) -> bool:
	...

def is_iterable_type(typ: type) -> bool:
	"""If the given type is `typing.Iterable[T]`"""
	...

def is_union_type(typ: type) -> bool:
	...

def is_required_type(typ: type) -> bool:
	...

def is_typevar(typ: type) -> bool:
	...

def strip_annotated_type(typ: type) -> type:
	...

def extract_type_arg(typ: type, index: int) -> type:
	...

def extract_type_var_from_base(typ: type, *, generic_bases: tuple[type, ...], index: int, failure_message: str | None = ...) -> type:
	"""Given a type like `Foo[T]`, returns the generic type variable `T`.

	This also handles the case where a concrete subclass is given, e.g.
	```py
	class MyResponse(Foo[bytes]):
	    ...

	extract_type_var(MyResponse, bases=(Foo,), index=0) -> bytes
	```

	And where a generic subclass is given:
	```py
	_T = TypeVar('_T')
	class MyResponse(Foo[_T]):
	    ...

	extract_type_var(MyResponse[bytes], bases=(Foo,), index=0) -> bytes
	```
	"""
	...

