"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from zai.core import BaseModel

class SearchIntent(BaseModel):
	index: int
	query: str
	intent: str
	keywords: str
	...


class SearchResult(BaseModel):
	index: int
	title: str
	link: str
	content: str
	icon: str
	media: str
	refer: str
	...


class SearchRecommend(BaseModel):
	index: int
	query: str
	...


class WebSearchMessageToolCall(BaseModel):
	id: str
	search_intent: Optional[SearchIntent]
	search_result: Optional[SearchResult]
	search_recommend: Optional[SearchRecommend]
	type: str
	...


class WebSearchMessage(BaseModel):
	role: str
	tool_calls: Optional[List[WebSearchMessageToolCall]] = ...


class WebSearchChoice(BaseModel):
	index: int
	finish_reason: str
	message: WebSearchMessage
	...


class WebSearch(BaseModel):
	created: Optional[int] = ...
	choices: List[WebSearchChoice]
	request_id: Optional[str] = ...
	id: Optional[str] = ...


