"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from zai.core import BaseModel

class FileObject(BaseModel):
	"""
	Represents a file object in the system.

	Attributes:
		id (Optional[str]): Unique identifier for the file
		bytes (Optional[int]): Size of the file in bytes
		created_at (Optional[int]): Timestamp when the file was created
		filename (Optional[str]): Name of the file
		object (Optional[str]): Object type identifier
		purpose (Optional[str]): Purpose of the file
		status (Optional[str]): Current status of the file
		status_details (Optional[str]): Additional details about the file status
	"""
	id: Optional[str] = ...
	bytes: Optional[int] = ...
	created_at: Optional[int] = ...
	filename: Optional[str] = ...
	object: Optional[str] = ...
	purpose: Optional[str] = ...
	status: Optional[str] = ...
	status_details: Optional[str] = ...


class ListOfFileObject(BaseModel):
	"""
	Represents a paginated list of file objects.

	Attributes:
		object (Optional[str]): Object type identifier
		data (List[FileObject]): List of file objects
		has_more (Optional[bool]): Whether there are more files available
	"""
	object: Optional[str] = ...
	data: List[FileObject]
	has_more: Optional[bool] = ...


