"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Optional
from zai.core import BaseModel

class UploadDetail(BaseModel):
	url: str
	knowledge_type: int
	file_name: Optional[str] = ...
	sentence_size: Optional[int] = ...
	custom_separator: Optional[List[str]] = ...
	callback_url: Optional[str] = ...
	callback_header: Optional[Dict[str, str]] = ...


