"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, FileTypes, Headers, NotGiven, cached_property
from zai.core._legacy_binary_response import HttpxBinaryResponseContent
from zai.types.audio import AudioSpeechChunk
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from .transcriptions import Transcriptions
from zai.core._streaming import StreamResponse
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Audio(BaseAPI):
	"""
	API resource for audio operations

	Attributes:
		transcriptions (Transcriptions): Audio transcription operations
	"""
	@cached_property
	def transcriptions(self) -> Transcriptions:
		...
	
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def speech(self, *, model: str, input: str = ..., voice: str = ..., response_format: str = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., request_id: str = ..., user_id: str = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ..., encode_format: str = ..., speed: float | None = ..., volume: float | None = ..., stream: bool | None = ...) -> HttpxBinaryResponseContent | StreamResponse[AudioSpeechChunk]:
		"""
		Generate speech audio from text input

		Arguments:
			model (str): The model to use for speech generation
			input (str): The text to convert to speech
			voice (str): The voice to use for speech generation
			response_format (str): The format of the response audio
			sensitive_word_check (Optional[SensitiveWordCheckRequest]): Sensitive word check configuration
			request_id (str): Unique identifier for the request
			user_id (str): User identifier
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
		"""
		...
	
	def customization(self, *, model: str, input: str = ..., voice_text: str = ..., voice_data: FileTypes = ..., response_format: str = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., request_id: str = ..., user_id: str = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ..., watermark_enabled: Optional[bool] | NotGiven = ...) -> HttpxBinaryResponseContent:
		"""
		Generate customized speech audio with voice cloning

		Arguments:
			model (str): The model to use for speech generation
			input (str): The text to convert to speech
			voice_text (str): Text for voice customization
			voice_data (FileTypes): Voice data file for customization
			response_format (str): The format of the response audio
			sensitive_word_check (Optional[SensitiveWordCheckRequest]): Sensitive word check configuration
			request_id (str): Unique identifier for the request
			user_id (str): User identifier
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
			watermark_enabled (Optional[bool]): Whether to enable watermark on generated audio
		"""
		...
	


