"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from typing_extensions import Literal
from zai.core import BaseAPI, Body, FileTypes, Headers, NotGiven, StreamResponse
from zai.types.chat.chat_completion import Completion
from zai.types.chat.chat_completion_chunk import ChatCompletionChunk
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from zai._client import ZaiClient

logger = ...
if TYPE_CHECKING:
	...
class Transcriptions(BaseAPI):
	"""
	API resource for audio transcription operations
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def create(self, *, file: FileTypes, model: str, request_id: Optional[str] | NotGiven = ..., user_id: Optional[str] | NotGiven = ..., stream: Optional[Literal[False]] | Literal[True] | NotGiven = ..., temperature: Optional[float] | NotGiven = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> Completion | StreamResponse[ChatCompletionChunk]:
		"""
		Transcribe audio files to text

		Arguments:
			file (FileTypes): Audio file to transcribe
			model (str): The model to use for transcription
			request_id (Optional[str]): Unique identifier for the request
			user_id (Optional[str]): User identifier
			stream (Optional[Literal[False]] | Literal[True]): Whether to stream the response
			temperature (Optional[float]): Sampling temperature for transcription
			sensitive_word_check (Optional[SensitiveWordCheckRequest]): Sensitive word check configuration
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
		"""
		...
	


