"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, TYPE_CHECKING
from typing_extensions import Literal
from zai.core import BaseAPI, Body, FileTypes, Headers, NotGiven, _legacy_response
from zai.types.files import FileDeleted, FileObject, ListOfFileObject, UploadDetail
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Files(BaseAPI):
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def create(self, *, file: FileTypes = ..., upload_detail: List[UploadDetail] = ..., purpose: Literal['fine-tune', 'retrieval', 'batch', 'voice-clone-input'], knowledge_id: str = ..., sentence_size: int = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> FileObject:
		...
	
	def list(self, *, purpose: str | NotGiven = ..., limit: int | NotGiven = ..., after: str | NotGiven = ..., order: str | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> ListOfFileObject:
		...
	
	def delete(self, file_id: str, *, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> FileDeleted:
		"""
		Delete a file.

		Args:
		  file_id: The ID of the file to delete
		  extra_headers: Send extra headers

		  extra_body: Add additional JSON properties to the request

		  timeout: Override the client-level default timeout for this request, in seconds
		"""
		...
	
	def content(self, file_id: str, *, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> _legacy_response.HttpxBinaryResponseContent:
		"""
		Returns the contents of the specified file.

		Args:
		  extra_headers: Send extra headers

		  extra_body: Add additional JSON properties to the request

		  timeout: Override the client-level default timeout for this request, in seconds
		"""
		...
	


class FilesWithRawResponse:
	def __init__(self, files: Files) -> None:
		...
	


