"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from zai.types.video import VideoObject
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Videos(BaseAPI):
	"""
	API resource for video generation operations
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def generations(self, *, model: str, prompt: str = ..., image_url: str | List[str] | dict | None = ..., quality: str = ..., with_audio: bool = ..., size: str = ..., duration: int = ..., fps: int = ..., style: str = ..., aspect_ratio: str = ..., off_peak: bool = ..., movement_amplitude: str = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., request_id: str = ..., user_id: str = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ..., watermark_enabled: Optional[bool] | NotGiven = ...) -> VideoObject:
		"""
		Generate videos from text prompts or images

		Arguments:
			model (str): The model to use for video generation
			prompt (str): Text description for video generation
			image_url (str | List[str] | dict): Image(s) for video generation (URL, Base64, or object)
			quality (str): Output mode, "quality" or "speed"
			with_audio (bool): Whether to include audio in the video
			size (str): Size/resolution of the generated video
			duration (int): Duration of the video in seconds
			fps (int): Frames per second for the video
			style (str): Style, e.g., "general", "anime"
			aspect_ratio (str): Aspect ratio, e.g., "16:9", "9:16", "1:1"
			movement_amplitude (str): Movement amplitude, e.g., "auto", "small", "medium", "large"
			sensitive_word_check (Optional[SensitiveWordCheckRequest]): Sensitive word check configuration
			request_id (str): Unique identifier for the request
			user_id (str): User identifier
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
			watermark_enabled (Optional[bool]): Whether to enable watermark on generated videos
		"""
		...
	
	def retrieve_videos_result(self, id: str, *, extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> VideoObject:
		"""
		Retrieve the result of a video generation operation

		Arguments:
			id (str): Unique identifier for the video generation operation
			extra_headers (Headers): Additional headers to send
			extra_body (Body): Additional body parameters
			timeout (float | httpx.Timeout): Request timeout
		"""
		...
	


