"""
This type stub file was generated by pyright.
"""

from ...._compat import cached_property
from ...._resource import AsyncAPIResource, SyncAPIResource
from .completions import AsyncCompletions, Completions

__all__ = ["Chat", "AsyncChat"]
class Chat(SyncAPIResource):
    @cached_property
    def completions(self) -> Completions:
        ...
    


class AsyncChat(AsyncAPIResource):
    @cached_property
    def completions(self) -> AsyncCompletions:
        ...
    


