"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Dict, Iterable, List, Optional, Union
from typing_extensions import Literal
from ...._compat import cached_property
from ...._resource import AsyncAPIResource, SyncAPIResource
from ...._types import Body, Headers, Query
from ...._utils import async_with_sts_token, with_sts_token
from ....types.chat import ChatCompletion, ChatCompletionMessageParam, ChatCompletionToolChoiceOptionParam, ChatCompletionToolParam, completion_create_params
from ...chat.completions import AsyncCompletionsWithRawResponse, CompletionsWithRawResponse

__all__ = ["Completions", "AsyncCompletions"]
class Completions(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> CompletionsWithRawResponse:
        ...
    
    @with_sts_token
    def create(self, *, messages: Iterable[ChatCompletionMessageParam], model: str, frequency_penalty: Optional[float] | None = ..., function_call: completion_create_params.FunctionCall | None = ..., logit_bias: Optional[Dict[str, int]] | None = ..., logprobs: Optional[bool] | None = ..., max_tokens: Optional[int] | None = ..., presence_penalty: Optional[float] | None = ..., stop: Union[Optional[str], List[str]] | None = ..., temperature: Optional[float] | None = ..., tools: Iterable[ChatCompletionToolParam] | None = ..., top_logprobs: Optional[int] | None = ..., top_p: Optional[float] | None = ..., repetition_penalty: Optional[float] | None = ..., n: Optional[int] | None = ..., parallel_tool_calls: Optional[bool] | None = ..., service_tier: Optional[Literal["auto", "default"]] | None = ..., tool_choice: ChatCompletionToolChoiceOptionParam | None = ..., response_format: completion_create_params.ResponseFormat | None = ..., thinking: completion_create_params.Thinking | None = ..., max_completion_tokens: Optional[int] | None = ..., user: str | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ChatCompletion:
        ...
    


class AsyncCompletions(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncCompletionsWithRawResponse:
        ...
    
    @async_with_sts_token
    async def create(self, *, messages: Iterable[ChatCompletionMessageParam], model: str, frequency_penalty: Optional[float] | None = ..., function_call: completion_create_params.FunctionCall | None = ..., logit_bias: Optional[Dict[str, int]] | None = ..., logprobs: Optional[bool] | None = ..., max_tokens: Optional[int] | None = ..., presence_penalty: Optional[float] | None = ..., stop: Union[Optional[str], List[str]] | None = ..., temperature: Optional[float] | None = ..., tools: Iterable[ChatCompletionToolParam] | None = ..., top_logprobs: Optional[int] | None = ..., top_p: Optional[float] | None = ..., user: str | None = ..., repetition_penalty: Optional[float] | None = ..., n: Optional[int] | None = ..., parallel_tool_calls: Optional[bool] | None = ..., service_tier: Optional[Literal["auto", "default"]] | None = ..., tool_choice: ChatCompletionToolChoiceOptionParam | None = ..., response_format: completion_create_params.ResponseFormat | None = ..., thinking: completion_create_params.Thinking | None = ..., max_completion_tokens: Optional[int] | None = ..., extra_headers: Headers | None = ..., extra_query: Query | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None = ...) -> ChatCompletion:
        ...
    


