"""
This type stub file was generated by pyright.
"""

from ..._compat import cached_property
from .chat.chat import AsyncChat, Chat
from ..._resource import AsyncAPIResource, SyncAPIResource

__all__ = ["Beta", "AsyncBeta"]
class Beta(SyncAPIResource):
    @cached_property
    def chat(self) -> Chat:
        ...
    
    @cached_property
    def with_raw_response(self) -> BetaWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.
        """
        ...
    
    @cached_property
    def with_streaming_response(self) -> BetaWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.
        """
        ...
    


class AsyncBeta(AsyncAPIResource):
    @cached_property
    def chat(self) -> AsyncChat:
        ...
    
    @cached_property
    def with_raw_response(self) -> AsyncBetaWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.
        """
        ...
    
    @cached_property
    def with_streaming_response(self) -> AsyncBetaWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.
        """
        ...
    


class BetaWithRawResponse:
    def __init__(self, beta: Beta) -> None:
        ...
    


class AsyncBetaWithRawResponse:
    def __init__(self, beta: AsyncBeta) -> None:
        ...
    


class BetaWithStreamingResponse:
    def __init__(self, beta: Beta) -> None:
        ...
    


class AsyncBetaWithStreamingResponse:
    def __init__(self, beta: AsyncBeta) -> None:
        ...
    


