"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Optional, TYPE_CHECKING
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.sensitive_word_check import SensitiveWordCheckRequest
from zai.types.web_search.web_search_resp import WebSearchResp
from zai._client import ZaiClient

logger = ...
if TYPE_CHECKING:
	...
class WebSearchApi(BaseAPI):
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def web_search(self, *, request_id: Optional[str] | NotGiven = ..., search_engine: Optional[str] | NotGiven = ..., search_query: Optional[str] | NotGiven = ..., user_id: Optional[str] | NotGiven = ..., sensitive_word_check: Optional[SensitiveWordCheckRequest] | NotGiven = ..., count: Optional[int] | NotGiven = ..., search_domain_filter: Optional[str] | NotGiven = ..., search_recency_filter: Optional[str] | NotGiven = ..., content_size: Optional[str] | NotGiven = ..., search_intent: Optional[bool] | NotGiven = ..., include_image: Optional[bool] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> WebSearchResp:
		...
	


