"""
This type stub file was generated by pyright.
"""

import httpx
from typing import List, Optional, TYPE_CHECKING, Union
from zai.core import BaseAPI, Body, Headers, NotGiven
from zai.types.embeddings import EmbeddingsResponded
from zai._client import ZaiClient

if TYPE_CHECKING:
	...
class Embeddings(BaseAPI):
	"""
	Embeddings API resource

	Attributes:
		client (ZaiClient): The ZAI client instance
	"""
	def __init__(self, client: ZaiClient) -> None:
		...
	
	def create(self, *, input: Union[str, List[str], List[int], List[List[int]]], model: Union[str], dimensions: Union[int] | NotGiven = ..., encoding_format: str | NotGiven = ..., user: str | NotGiven = ..., request_id: Optional[str] | NotGiven = ..., sensitive_word_check: Optional[object] | NotGiven = ..., extra_headers: Headers | None = ..., extra_body: Body | None = ..., disable_strict_validation: Optional[bool] | None = ..., timeout: float | httpx.Timeout | None | NotGiven = ...) -> EmbeddingsResponded:
		"""
		Create embeddings for the given input

		Arguments:
			input (Union[str, List[str], List[int], List[List[int]]]): Input text or tokens to embed
			model (str): Model name to use for embedding generation
			dimensions (Union[int]): Number of dimensions for the embedding vectors
			encoding_format (str): Format for encoding the embeddings
			user (str): User identifier
			request_id (Optional[str]): Request identifier
			sensitive_word_check (Optional[object]): Sensitive word checking configuration
			extra_headers (Headers): Additional HTTP headers
			extra_body (Body): Additional request body parameters
			disable_strict_validation (Optional[bool]): Whether to disable strict validation
			timeout (float | httpx.Timeout): Request timeout
		"""
		...
	


