"""
This type stub file was generated by pyright.
"""

from .voice_clone_params import VoiceCloneParams
from .voice_delete_params import VoiceDeleteParams
from .voice_list_params import VoiceListParams
from .voice_object import VoiceCloneResult, VoiceData, VoiceDeleteResult, VoiceListResult

__all__ = ['VoiceCloneParams', 'VoiceDeleteParams', 'VoiceListParams', 'VoiceCloneResult', 'VoiceDeleteResult', 'VoiceData', 'VoiceListResult']
