"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from .._client import ZaiClient

if TYPE_CHECKING:
	...
class BaseAPI:
	"""
	Base class for all API resource classes.

	Provides common functionality and HTTP method shortcuts for API resources.
	All API resource classes should inherit from this base class.

	Attributes:
		_client (ZaiClient): The client instance for making API requests
	"""
	_client: ZaiClient
	def __init__(self, client: ZaiClient) -> None:
		"""
		Initialize the API resource with a client instance.

		Args:
			client (ZaiClient): The client instance for making API requests
		"""
		...
	


