"""
This type stub file was generated by pyright.
"""

import httpx

__all__ = ['ZaiError', 'APIStatusError', 'APIRequestFailedError', 'APIAuthenticationError', 'APIReachLimitError', 'APIInternalError', 'APIServerFlowExceedError', 'APIResponseError', 'APIResponseValidationError', 'APITimeoutError', 'APIConnectionError']
class ZaiError(Exception):
	def __init__(self, message: str) -> None:
		...
	


class APIStatusError(ZaiError):
	response: httpx.Response
	status_code: int
	def __init__(self, message: str, *, response: httpx.Response) -> None:
		...
	


class APIRequestFailedError(APIStatusError):
	...


class APIAuthenticationError(APIStatusError):
	...


class APIReachLimitError(APIStatusError):
	...


class APIInternalError(APIStatusError):
	...


class APIServerFlowExceedError(APIStatusError):
	...


class APIResponseError(ZaiError):
	message: str
	request: httpx.Request
	json_data: object
	def __init__(self, message: str, request: httpx.Request, json_data: object) -> None:
		...
	


class APIResponseValidationError(APIResponseError):
	status_code: int
	response: httpx.Response
	def __init__(self, response: httpx.Response, json_data: object | None, *, message: str | None = ...) -> None:
		...
	


class APIConnectionError(APIResponseError):
	def __init__(self, *, message: str = ..., request: httpx.Request) -> None:
		...
	


class APITimeoutError(APIConnectionError):
	def __init__(self, request: httpx.Request) -> None:
		...
	


