"""
This type stub file was generated by pyright.
"""

from typing import overload
from typing_extensions import TypeGuard
from ._base_type import FileContent, HttpxRequestFiles, RequestFiles

def is_file_content(obj: object) -> TypeGuard[FileContent]:
	...

def assert_is_file_content(obj: object, *, key: str | None = ...) -> None:
	...

@overload
def to_httpx_files(files: None) -> None:
	...

@overload
def to_httpx_files(files: RequestFiles) -> HttpxRequestFiles:
	...

def to_httpx_files(files: RequestFiles | None) -> HttpxRequestFiles | None:
	...

