"""
This type stub file was generated by pyright.
"""

import json
from typing import Any

"""JSON encoding utilities for BaseModel objects."""
class ZAIJSONEncoder(json.JSONEncoder):
    """Custom JSON encoder that handles BaseModel objects."""
    def default(self, obj: Any) -> Any:
        """Override default method to handle BaseModel objects."""
        ...
    


def json_dumps(obj: Any, **kwargs) -> str:
    """
    JSON dumps with support for BaseModel objects.
    
    Args:
        obj: Object to serialize
        **kwargs: Additional arguments to pass to json.dumps()
        
    Returns:
        JSON string representation
    """
    ...

def json_loads(s: str, **kwargs) -> Any:
    """
    JSON loads with consistent interface.
    
    Args:
        s: JSON string to deserialize
        **kwargs: Additional arguments to pass to json.loads()
        
    Returns:
        Deserialized object
    """
    ...

