"""
This type stub file was generated by pyright.
"""

import cachetools.func

CACHE_TTL_SECONDS = ...
API_TOKEN_TTL_SECONDS = ...
@cachetools.func.ttl_cache(maxsize=10, ttl=CACHE_TTL_SECONDS)
def generate_token(apikey: str): # -> str:
	...

