"""
This type stub file was generated by pyright.
"""

import datetime
import logging
import httpx
from typing import Any, Callable, Generic, TYPE_CHECKING, TypeVar, overload
from typing_extensions import ParamSpec, override
from ._streaming import StreamResponse
from ._http_client import HttpClient
from ._request_opt import FinalRequestOptions

if TYPE_CHECKING:
	...
P = ParamSpec('P')
R = TypeVar('R')
_T = TypeVar('_T')
log: logging.Logger = ...
class LegacyAPIResponse(Generic[R]):
	"""This is a legacy class as it will be replaced by `APIResponse`
	and `AsyncAPIResponse` in the `_response.py` file in the next major
	release.

	For the sync client this will mostly be the same with the exception
	of `content` & `text` will be methods instead of properties. In the
	async client, all methods will be async.

	A migration script will be provided & the migration in general should
	be smooth.
	"""
	_cast_type: type[R]
	_client: HttpClient
	_parsed_by_type: dict[type[Any], Any]
	_stream: bool
	_stream_cls: type[StreamResponse[Any]] | None
	_options: FinalRequestOptions
	http_response: httpx.Response
	def __init__(self, *, raw: httpx.Response, cast_type: type[R], client: HttpClient, stream: bool, stream_cls: type[StreamResponse[Any]] | None, options: FinalRequestOptions) -> None:
		...
	
	@property
	def request_id(self) -> str | None:
		...
	
	@overload
	def parse(self, *, to: type[_T]) -> _T:
		...
	
	@overload
	def parse(self) -> R:
		...
	
	def parse(self, *, to: type[_T] | None = ...) -> R | _T:
		"""Returns the rich python representation of this response's data.

		NOTE: For the async client: this will become a coroutine in the next major version.

		For lower-level control, see `.read()`, `.json()`, `.iter_bytes()`.

		You can customise the type that the response is parsed into through
		the `to` argument, e.g.

		```py
		from zai import BaseModel


		class MyModel(BaseModel):
		    foo: str


		obj = response.parse(to=MyModel)
		print(obj.foo)
		```

		We support parsing:
		  - `BaseModel`
		  - `dict`
		  - `list`
		  - `Union`
		  - `str`
		  - `int`
		  - `float`
		  - `httpx.Response`
		"""
		...
	
	@property
	def headers(self) -> httpx.Headers:
		...
	
	@property
	def http_request(self) -> httpx.Request:
		...
	
	@property
	def status_code(self) -> int:
		...
	
	@property
	def url(self) -> httpx.URL:
		...
	
	@property
	def method(self) -> str:
		...
	
	@property
	def content(self) -> bytes:
		"""Return the binary response content.

		NOTE: this will be removed in favour of `.read()` in the
		next major version.
		"""
		...
	
	@property
	def text(self) -> str:
		"""Return the decoded response content.

		NOTE: this will be turned into a method in the next major version.
		"""
		...
	
	@property
	def http_version(self) -> str:
		...
	
	@property
	def is_closed(self) -> bool:
		...
	
	@property
	def elapsed(self) -> datetime.timedelta:
		"""The time taken for the complete request/response cycle to complete."""
		...
	
	@override
	def __repr__(self) -> str:
		...
	


class MissingStreamClassError(TypeError):
	def __init__(self) -> None:
		...
	


def to_raw_response_wrapper(func: Callable[P, R]) -> Callable[P, LegacyAPIResponse[R]]:
	"""Higher order function that takes one of our bound API methods and wraps it
	to support returning the raw `APIResponse` object directly.
	"""
	...

