"""
This type stub file was generated by pyright.
"""

import os
import httpx
from typing import Any, AsyncIterator, Iterator

class HttpxResponseContent:
	@property
	def content(self) -> bytes:
		...
	
	@property
	def text(self) -> str:
		...
	
	@property
	def encoding(self) -> str | None:
		...
	
	@property
	def charset_encoding(self) -> str | None:
		...
	
	def json(self, **kwargs: Any) -> Any:
		...
	
	def read(self) -> bytes:
		...
	
	def iter_bytes(self, chunk_size: int | None = ...) -> Iterator[bytes]:
		...
	
	def iter_text(self, chunk_size: int | None = ...) -> Iterator[str]:
		...
	
	def iter_lines(self) -> Iterator[str]:
		...
	
	def iter_raw(self, chunk_size: int | None = ...) -> Iterator[bytes]:
		...
	
	def write_to_file(self, file: str | os.PathLike[str]) -> None:
		...
	
	def stream_to_file(self, file: str | os.PathLike[str], *, chunk_size: int | None = ...) -> None:
		...
	
	def close(self) -> None:
		...
	
	async def aread(self) -> bytes:
		...
	
	async def aiter_bytes(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]:
		...
	
	async def aiter_text(self, chunk_size: int | None = ...) -> AsyncIterator[str]:
		...
	
	async def aiter_lines(self) -> AsyncIterator[str]:
		...
	
	async def aiter_raw(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]:
		...
	
	async def astream_to_file(self, file: str | os.PathLike[str], *, chunk_size: int | None = ...) -> None:
		...
	
	async def aclose(self) -> None:
		...
	


class HttpxBinaryResponseContent(HttpxResponseContent):
	response: httpx.Response
	def __init__(self, response: httpx.Response) -> None:
		...
	
	@property
	def content(self) -> bytes:
		...
	
	@property
	def encoding(self) -> str | None:
		...
	
	@property
	def charset_encoding(self) -> str | None:
		...
	
	def read(self) -> bytes:
		...
	
	def text(self) -> str:
		...
	
	def json(self, **kwargs: Any) -> Any:
		...
	
	def iter_text(self, chunk_size: int | None = ...) -> Iterator[str]:
		...
	
	def iter_lines(self) -> Iterator[str]:
		...
	
	async def aiter_text(self, chunk_size: int | None = ...) -> AsyncIterator[str]:
		...
	
	async def aiter_lines(self) -> AsyncIterator[str]:
		...
	
	def iter_bytes(self, chunk_size: int | None = ...) -> Iterator[bytes]:
		...
	
	def iter_raw(self, chunk_size: int | None = ...) -> Iterator[bytes]:
		...
	
	def write_to_file(self, file: str | os.PathLike[str]) -> None:
		"""Write the output to the given file.

		Accepts a filename or any path-like object, e.g. pathlib.Path

		Note: if you want to stream the data to the file instead of writing
		all at once then you should use `.with_streaming_response` when making
		the API request, e.g. `client.with_streaming_response.foo().stream_to_file('my_filename.txt')`
		"""
		...
	
	def stream_to_file(self, file: str | os.PathLike[str], *, chunk_size: int | None = ...) -> None:
		...
	
	def close(self) -> None:
		...
	
	async def aread(self) -> bytes:
		...
	
	async def aiter_bytes(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]:
		...
	
	async def aiter_raw(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]:
		...
	
	async def astream_to_file(self, file: str | os.PathLike[str], *, chunk_size: int | None = ...) -> None:
		...
	
	async def aclose(self) -> None:
		...
	


class HttpxTextBinaryResponseContent(HttpxBinaryResponseContent):
	response: httpx.Response
	@property
	def text(self) -> str:
		...
	
	def json(self, **kwargs: Any) -> Any:
		...
	
	def iter_text(self, chunk_size: int | None = ...) -> Iterator[str]:
		...
	
	def iter_lines(self) -> Iterator[str]:
		...
	
	async def aiter_text(self, chunk_size: int | None = ...) -> AsyncIterator[str]:
		...
	
	async def aiter_lines(self) -> AsyncIterator[str]:
		...
	


