"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING, Union
from httpx import Timeout
from typing_extensions import Callable, ClassVar, Required, TypedDict, Unpack, final
from ._base_compat import ConfigDict, PYDANTIC_V2
from ._base_type import AnyMapping, Body, Headers, HttpxRequestFiles, NotGiven, Query

class UserRequestInput(TypedDict, total=False):
	headers: Headers
	max_retries: int
	timeout: float | Timeout | None
	params: Query
	extra_json: AnyMapping
	...


class FinalRequestOptionsInput(TypedDict, total=False):
	method: Required[str]
	url: Required[str]
	params: Query
	headers: Headers
	max_retries: int
	timeout: float | Timeout | None
	files: HttpxRequestFiles | None
	json_data: Body
	extra_json: AnyMapping
	...


@final
class FinalRequestOptions(pydantic.BaseModel):
	method: str
	url: str
	params: Query = ...
	headers: Union[Headers, NotGiven] = ...
	max_retries: Union[int, NotGiven] = ...
	timeout: Union[float, Timeout, None, NotGiven] = ...
	files: Union[HttpxRequestFiles, None] = ...
	idempotency_key: Union[str, None] = ...
	post_parser: Union[Callable[[Any], Any], NotGiven] = ...
	json_data: Union[Body, None] = ...
	extra_json: Union[AnyMapping, None] = ...
	if PYDANTIC_V2:
		model_config: ClassVar[ConfigDict] = ...
	else:
		class Config(pydantic.BaseConfig):
			arbitrary_types_allowed: bool = ...
		
		
	def get_max_retries(self, max_retries: int) -> int:
		...
	
	@classmethod
	def construct(cls, _fields_set: set[str] | None = ..., **values: Unpack[UserRequestInput]) -> FinalRequestOptions:
		...
	
	if not TYPE_CHECKING:
		...


