"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Generic, Iterator, TYPE_CHECKING, Type
from typing_extensions import TypeGuard
from ._base_type import ResponseT
from ._http_client import HttpClient

_FIELD_SEPARATOR = ...
if TYPE_CHECKING:
	...
class StreamResponse(Generic[ResponseT]):
	"""
	Stream response class, used to stream response from server.

	Attributes:
		response: The response from server.
		_cast_type: The type of response.
	"""
	response: httpx.Response
	_cast_type: Type[ResponseT]
	def __init__(self, *, cast_type: Type[ResponseT], response: httpx.Response, client: HttpClient) -> None:
		...
	
	def __next__(self) -> ResponseT:
		...
	
	def __iter__(self) -> Iterator[ResponseT]:
		...
	
	def __stream__(self) -> Iterator[ResponseT]:
		...
	


class Event:
	def __init__(self, event: str | None = ..., data: str | None = ..., id: str | None = ..., retry: int | None = ...) -> None:
		...
	
	def __repr__(self): # -> str:
		...
	
	@property
	def event(self): # -> str | None:
		...
	
	@property
	def data(self): # -> str | None:
		...
	
	def json_data(self): # -> Any:
		...
	
	@property
	def id(self): # -> str | None:
		...
	
	@property
	def retry(self): # -> int | None:
		...
	


class SSELineParser:
	_data: list[str]
	_event: str | None
	_retry: int | None
	_id: str | None
	def __init__(self) -> None:
		...
	
	def iter_lines(self, lines: Iterator[str]) -> Iterator[Event]:
		...
	
	def decode_line(self, line: str): # -> None:
		...
	


def is_stream_class_type(typ: type) -> TypeGuard[type[StreamResponse[object]]]:
	"""TypeGuard for determining whether or not the given type is a subclass of `Stream` / `AsyncStream`"""
	...

def extract_stream_chunk_type(stream_cls: type, *, failure_message: str | None = ...) -> type:
	"""Given a type like `StreamResponse[T]`, returns the generic type variable `T`.

	This also handles the case where a concrete subclass is given, e.g.
	```py
	class MyStream(StreamResponse[bytes]):
	    ...

	extract_stream_chunk_type(MyStream) -> bytes
	```
	"""
	...

