"""
This type stub file was generated by pyright.
"""

from typing import Generic, List, Optional, TypeVar
from typing_extensions import Protocol, override, runtime_checkable
from ._http_client import BasePage, BaseSyncPage, PageInfo

__all__ = ['SyncPage', 'SyncCursorPage']
_T = TypeVar('_T')
@runtime_checkable
class CursorPageItem(Protocol):
	id: Optional[str]
	...


class SyncPage(BaseSyncPage[_T], BasePage[_T], Generic[_T]):
	"""Note: no pagination actually occurs yet, this is for forwards-compatibility."""
	data: List[_T]
	object: str
	@override
	def next_page_info(self) -> None:
		"""
		This page represents a response that isn't actually paginated at the API level
		so there will never be a next page.
		"""
		...
	


class SyncCursorPage(BaseSyncPage[_T], BasePage[_T], Generic[_T]):
	data: List[_T]
	@override
	def next_page_info(self) -> Optional[PageInfo]:
		...
	


